#ifndef RCIMAGERESOURCES_H
#define RCIMAGERESOURCES_H

//
// NOTE:
// this is the RealCAD image (bitmap,icon,cursor) resource definition file
// use this file in place of the Windows .rc file.
// This file was generated from a windows .rc file by rcimgtoc.exe
// if you edit it your changes may be overwritten later.
//

struct RCnumberedResourceImages {
    unsigned int id; // the number
    char *typeName; // bitmap, icon, cursor etc.
    char *fileName; // the file name of the resource
};
static RCnumberedResourceImages RCnumberedBitmapResources [] = {
    { 101 , "BITMAP" , "bmp101.bmp" } ,
    { 102 , "BITMAP" , "bmp102.bmp" } ,
    { 103 , "BITMAP" , "bmp103.bmp" } ,
    { 104 , "BITMAP" , "bmp104.bmp" } ,
    { 0 , "BITMAP" , "" } // last item
};
static int RC_NUM_NUMBERED_BITMAP_RESOURCES = sizeof(RCnumberedBitmapResources)/sizeof(RCnumberedResourceImages);

struct RCnamedResourceImages {
    char *name; // nemonic could be a number
    char *typeName; // bitmap, icon, cursor etc.
    char *fileName; // the file name of the resource
};
static RCnamedResourceImages RCnamedBitmapResources [] = {
    { "ARBOM_BITMAP" ,           "BITMAP" ,                 "arbom_bi.bmp" } ,
    { "ARC0_BITMAP" ,            "BITMAP" ,                 "arc0_bit.bmp" } ,
    { "ARC1_BITMAP" ,            "BITMAP" ,                 "arc1_bit.bmp" } ,
    { "ARC2_BITMAP" ,            "BITMAP" ,                 "arc2_bit.bmp" } ,
    { "ARC3_BITMAP" ,            "BITMAP" ,                 "arc3_bit.bmp" } ,
    { "ARC4_BITMAP" ,            "BITMAP" ,                 "arc4_bit.bmp" } ,
    { "ARCOST_BITMAP" ,          "BITMAP" ,                 "arcost_b.bmp" } ,
    { "ARDETAIL_BITMAP" ,        "BITMAP" ,                 "ardetail.bmp" } ,
    { "ARDOOR_BITMAP" ,          "BITMAP" ,                 "ardoor_b.bmp" } ,
    { "ARELEVATION_BITMAP" ,     "BITMAP" ,                 "arelevat.bmp" } ,
    { "ARFLOOR_BITMAP" ,         "BITMAP" ,                 "arfloor_.bmp" } ,
    { "ARGRID_BITMAP" ,          "BITMAP" ,                 "argrid_b.bmp" } ,
    { "ARINSERTCEILING_BITMAP" , "BITMAP" ,                 "arinsert.bmp" } ,
    { "ARINSERTFLOOR_BITMAP" ,   "BITMAP" ,                 "bmp00001.bmp" } ,
    { "ARNOTATION_BITMAP" ,      "BITMAP" ,                 "arnotati.bmp" } ,
    { "ARPERSPECTIVE_BITMAP" ,   "BITMAP" ,                 "arperspe.bmp" } ,
    { "ARROOF_BITMAP" ,          "BITMAP" ,                 "arroof_b.bmp" } ,
    { "ARSECTION_BITMAP" ,       "BITMAP" ,                 "arsectio.bmp" } ,
    { "ARSTAIRS_BITMAP" ,        "BITMAP" ,                 "arstairs.bmp" } ,
    { "ARSYMBOLS_BITMAP" ,       "BITMAP" ,                 "arsymbol.bmp" } ,
    { "ARTRIM_BITMAP" ,          "BITMAP" ,                 "artrim_b.bmp" } ,
    { "ARTRIMCORNER_BITMAP" ,    "BITMAP" ,                 "artrimco.bmp" } ,
    { "ARWALL_BITMAP" ,          "BITMAP" ,                 "arwall_b.bmp" } ,
    { "ARWALLDEFAULTS_BITMAP" ,  "BITMAP" ,                 "arwallde.bmp" } ,
    { "ARWINDOW_BITMAP" ,        "BITMAP" ,                 "arwindow.bmp" } ,
    { "BASIC1_BITMAP" ,          "BITMAP" ,                 "basic1_b.bmp" } ,
    { "BASIC2_BITMAP" ,          "BITMAP" ,                 "basic2_b.bmp" } ,
    { "BASIC3_BITMAP" ,          "BITMAP" ,                 "basic3_b.bmp" } ,
    { "BASIC4_BITMAP" ,          "BITMAP" ,                 "basic4_b.bmp" } ,
    { "BASIC5_BITMAP" ,          "BITMAP" ,                 "basic5_b.bmp" } ,
    { "BASIC6_BITMAP" ,          "BITMAP" ,                 "basic6_b.bmp" } ,
    { "BASIC7_BITMAP" ,          "BITMAP" ,                 "basic7_b.bmp" } ,
    { "BITMAP1_BITMAP" ,         "BITMAP" ,                 "bitmap1_.bmp" } ,
    { "BITMAP2_BITMAP" ,         "BITMAP" ,                 "bitmap2_.bmp" } ,
    { "CIRCLE0_BITMAP" ,         "BITMAP" ,                 "circle0_.bmp" } ,
    { "CIRCLE1_BITMAP" ,         "BITMAP" ,                 "circle1_.bmp" } ,
    { "CIRCLE2_BITMAP" ,         "BITMAP" ,                 "circle2_.bmp" } ,
    { "CIRCLE3_BITMAP" ,         "BITMAP" ,                 "circle3_.bmp" } ,
    { "CIRCLE4_BITMAP" ,         "BITMAP" ,                 "circle4_.bmp" } ,
    { "COLOUR_BITMAP" ,          "BITMAP" ,                 "colour_b.bmp" } ,
    { "COMPOSE1_BITMAP" ,        "BITMAP" ,                 "compose1.bmp" } ,
    { "COMPOSE2_BITMAP" ,        "BITMAP" ,                 "compose2.bmp" } ,
    { "COMPOSE3_BITMAP" ,        "BITMAP" ,                 "compose3.bmp" } ,
    { "COMPOSE4_BITMAP" ,        "BITMAP" ,                 "compose4.bmp" } ,
    { "COMPOSE5_BITMAP" ,        "BITMAP" ,                 "compose5.bmp" } ,
    { "COMPOSE6_BITMAP" ,        "BITMAP" ,                 "compose6.bmp" } ,
    { "COMPOSE7_BITMAP" ,        "BITMAP" ,                 "compose7.bmp" } ,
    { "CREATEWINDOW_BITMAP" ,    "BITMAP" ,                 "createwi.bmp" } ,
    { "CURVE0_BITMAP" ,          "BITMAP" ,                 "curve0_b.bmp" } ,
    { "CURVE1_BITMAP" ,          "BITMAP" ,                 "curve1_b.bmp" } ,
    { "CURVE2_BITMAP" ,          "BITMAP" ,                 "curve2_b.bmp" } ,
    { "CURVE3_BITMAP" ,          "BITMAP" ,                 "curve3_b.bmp" } ,
    { "CURVE4_BITMAP" ,          "BITMAP" ,                 "curve4_b.bmp" } ,
    { "CURVE5_BITMAP" ,          "BITMAP" ,                 "curve5_b.bmp" } ,
    { "CURVE6_BITMAP" ,          "BITMAP" ,                 "curve6_b.bmp" } ,
    { "DIMEN0_BITMAP" ,          "BITMAP" ,                 "dimen0_b.bmp" } ,
    { "DIMEN1_BITMAP" ,          "BITMAP" ,                 "dimen1_b.bmp" } ,
    { "DIMEN10_BITMAP" ,         "BITMAP" ,                 "dimen10_.bmp" } ,
    { "DIMEN2_BITMAP" ,          "BITMAP" ,                 "dimen2_b.bmp" } ,
    { "DIMEN3_BITMAP" ,          "BITMAP" ,                 "dimen3_b.bmp" } ,
    { "DIMEN4_BITMAP" ,          "BITMAP" ,                 "dimen4_b.bmp" } ,
    { "DIMEN5_BITMAP" ,          "BITMAP" ,                 "dimen5_b.bmp" } ,
    { "DIMEN6_BITMAP" ,          "BITMAP" ,                 "dimen6_b.bmp" } ,
    { "DIMEN7_BITMAP" ,          "BITMAP" ,                 "dimen7_b.bmp" } ,
    { "DIMEN8_BITMAP" ,          "BITMAP" ,                 "dimen8_b.bmp" } ,
    { "DIMEN9_BITMAP" ,          "BITMAP" ,                 "dimen9_b.bmp" } ,
    { "DISPLAYMASK0_BITMAP" ,    "BITMAP" ,                 "displaym.bmp" } ,
    { "ELLIPSE1_BITMAP" ,        "BITMAP" ,                 "ellipse1.bmp" } ,
    { "ELLIPSE2_BITMAP" ,        "BITMAP" ,                 "ellipse2.bmp" } ,
    { "FIGURE0_BITMAP" ,         "BITMAP" ,                 "figure0_.bmp" } ,
    { "FIGURE1_BITMAP" ,         "BITMAP" ,                 "figure1_.bmp" } ,
    { "FIGURE2_BITMAP" ,         "BITMAP" ,                 "figure2_.bmp" } ,
    { "FIGURE3_BITMAP" ,         "BITMAP" ,                 "figure3_.bmp" } ,
    { "FIGURE4_BITMAP" ,         "BITMAP" ,                 "figure4_.bmp" } ,
    { "GROUP1_BITMAP" ,          "BITMAP" ,                 "group1_b.bmp" } ,
    { "GROUP2_BITMAP" ,          "BITMAP" ,                 "group2_b.bmp" } ,
    { "GROUP3_BITMAP" ,          "BITMAP" ,                 "group3_b.bmp" } ,
    { "GROUP4_BITMAP" ,          "BITMAP" ,                 "group4_b.bmp" } ,
    { "LAYER_BITMAP" ,           "BITMAP" ,                 "layer_bi.bmp" } ,
    { "LINE0_BITMAP" ,           "BITMAP" ,                 "line0_bi.bmp" } ,
    { "LINE1_BITMAP" ,           "BITMAP" ,                 "line1_bi.bmp" } ,
    { "LINE2_BITMAP" ,           "BITMAP" ,                 "line2_bi.bmp" } ,
    { "LINE3_BITMAP" ,           "BITMAP" ,                 "line3_bi.bmp" } ,
    { "LINE4_BITMAP" ,           "BITMAP" ,                 "line4_bi.bmp" } ,
    { "LINE5_BITMAP" ,           "BITMAP" ,                 "line5_bi.bmp" } ,
    { "LINE6_BITMAP" ,           "BITMAP" ,                 "line6_bi.bmp" } ,
    { "LINE7_BITMAP" ,           "BITMAP" ,                 "line7_bi.bmp" } ,
    { "LINE8_BITMAP" ,           "BITMAP" ,                 "line8_bi.bmp" } ,
    { "MASK1_BITMAP" ,           "BITMAP" ,                 "mask1_bi.bmp" } ,
    { "MASK2_BITMAP" ,           "BITMAP" ,                 "mask2_bi.bmp" } ,
    { "MASK3_BITMAP" ,           "BITMAP" ,                 "mask3_bi.bmp" } ,
    { "MASK4_BITMAP" ,           "BITMAP" ,                 "mask4_bi.bmp" } ,
    { "MASK5_BITMAP" ,           "BITMAP" ,                 "mask5_bi.bmp" } ,
    { "MEASURE0_BITMAP" ,        "BITMAP" ,                 "measure0.bmp" } ,
    { "MEASURE1_BITMAP" ,        "BITMAP" ,                 "measure1.bmp" } ,
    { "MEASURE2_BITMAP" ,        "BITMAP" ,                 "measure2.bmp" } ,
    { "MEASURE3_BITMAP" ,        "BITMAP" ,                 "measure3.bmp" } ,
    { "NC1_BITMAP" ,             "BITMAP" ,                 "nc1_bitm.bmp" } ,
    { "NC2_BITMAP" ,             "BITMAP" ,                 "nc2_bitm.bmp" } ,
    { "NC3_BITMAP" ,             "BITMAP" ,                 "nc3_bitm.bmp" } ,
    { "NC4_BITMAP" ,             "BITMAP" ,                 "nc4_bitm.bmp" } ,
    { "NC5_BITMAP" ,             "BITMAP" ,                 "nc5_bitm.bmp" } ,
    { "NC6_BITMAP" ,             "BITMAP" ,                 "nc6_bitm.bmp" } ,
    { "PAINT0_BITMAP" ,          "BITMAP" ,                 "paint0_b.bmp" } ,
    { "PATCH1_BITMAP" ,          "BITMAP" ,                 "patch1_b.bmp" } ,
    { "PATCH2_BITMAP" ,          "BITMAP" ,                 "patch2_b.bmp" } ,
    { "PATCH3_BITMAP" ,          "BITMAP" ,                 "patch3_b.bmp" } ,
    { "POINT0_BITMAP" ,          "BITMAP" ,                 "point0_b.bmp" } ,
    { "POINT1_BITMAP" ,          "BITMAP" ,                 "point1_b.bmp" } ,
    { "POINT2_BITMAP" ,          "BITMAP" ,                 "point2_b.bmp" } ,
    { "POSITION0_BITMAP" ,       "BITMAP" ,                 "position.bmp" } ,
    { "POSITION1_BITMAP" ,       "BITMAP" ,                 "bmp00002.bmp" } ,
    { "POSITION2_BITMAP" ,       "BITMAP" ,                 "bmp00003.bmp" } ,
    { "POSITION3_BITMAP" ,       "BITMAP" ,                 "bmp00004.bmp" } ,
    { "POSITION4_BITMAP" ,       "BITMAP" ,                 "bmp00005.bmp" } ,
    { "POSITION5_BITMAP" ,       "BITMAP" ,                 "bmp00006.bmp" } ,
    { "POSITION6_BITMAP" ,       "BITMAP" ,                 "bmp00007.bmp" } ,
    { "POSITION7_BITMAP" ,       "BITMAP" ,                 "bmp00008.bmp" } ,
    { "PRINTPREVIEW1_BITMAP" ,   "BITMAP" ,                 "printpre.bmp" } ,
    { "PRINTPREVIEW2_BITMAP" ,   "BITMAP" ,                 "bmp00009.bmp" } ,
    { "PRINTPREVIEW3_BITMAP" ,   "BITMAP" ,                 "bmp00010.bmp" } ,
    { "PRINTPREVIEW4_BITMAP" ,   "BITMAP" ,                 "bmp00011.bmp" } ,
    { "REDO_BITMAP" ,            "BITMAP" ,                 "redo_bit.bmp" } ,
    { "RESETWINDOW_BITMAP" ,     "BITMAP" ,                 "resetwin.bmp" } ,
    { "SELECTIONMASK0_BITMAP" ,  "BITMAP" ,                 "selectio.bmp" } ,
    { "SIMULATION1_BITMAP" ,     "BITMAP" ,                 "simulati.bmp" } ,
    { "SIMULATION10_BITMAP" ,    "BITMAP" ,                 "bmp00012.bmp" } ,
    { "SIMULATION11_BITMAP" ,    "BITMAP" ,                 "bmp00013.bmp" } ,
    { "SIMULATION12_BITMAP" ,    "BITMAP" ,                 "bmp00014.bmp" } ,
    { "SIMULATION2_BITMAP" ,     "BITMAP" ,                 "bmp00015.bmp" } ,
    { "SIMULATION3_BITMAP" ,     "BITMAP" ,                 "bmp00016.bmp" } ,
    { "SIMULATION4_BITMAP" ,     "BITMAP" ,                 "bmp00017.bmp" } ,
    { "SIMULATION5_BITMAP" ,     "BITMAP" ,                 "bmp00018.bmp" } ,
    { "SIMULATION6_BITMAP" ,     "BITMAP" ,                 "bmp00019.bmp" } ,
    { "SIMULATION7_BITMAP" ,     "BITMAP" ,                 "bmp00020.bmp" } ,
    { "SIMULATION8_BITMAP" ,     "BITMAP" ,                 "bmp00021.bmp" } ,
    { "SIMULATION9_BITMAP" ,     "BITMAP" ,                 "bmp00022.bmp" } ,
    { "STYLE_BITMAP" ,           "BITMAP" ,                 "style_bi.bmp" } ,
    { "SURFACE0_BITMAP" ,        "BITMAP" ,                 "surface0.bmp" } ,
    { "SURFACE1_BITMAP" ,        "BITMAP" ,                 "surface1.bmp" } ,
    { "SURFACE2_BITMAP" ,        "BITMAP" ,                 "surface2.bmp" } ,
    { "SURFACE3_BITMAP" ,        "BITMAP" ,                 "surface3.bmp" } ,
    { "SURFACE4_BITMAP" ,        "BITMAP" ,                 "surface4.bmp" } ,
    { "SURFACE5_BITMAP" ,        "BITMAP" ,                 "surface5.bmp" } ,
    { "SURFACE6_BITMAP" ,        "BITMAP" ,                 "surface6.bmp" } ,
    { "TEXT0_BITMAP" ,           "BITMAP" ,                 "text0_bi.bmp" } ,
    { "TEXT1_BITMAP" ,           "BITMAP" ,                 "text1_bi.bmp" } ,
    { "TEXT2_BITMAP" ,           "BITMAP" ,                 "text2_bi.bmp" } ,
    { "TEXT3_BITMAP" ,           "BITMAP" ,                 "text3_bi.bmp" } ,
    { "TEXT4_BITMAP" ,           "BITMAP" ,                 "text4_bi.bmp" } ,
    { "TRIM0_BITMAP" ,           "BITMAP" ,                 "trim0_bi.bmp" } ,
    { "TRIM1_BITMAP" ,           "BITMAP" ,                 "trim1_bi.bmp" } ,
    { "TRIM10_BITMAP" ,          "BITMAP" ,                 "trim10_b.bmp" } ,
    { "TRIM11_BITMAP" ,          "BITMAP" ,                 "trim11_b.bmp" } ,
    { "TRIM2_BITMAP" ,           "BITMAP" ,                 "trim2_bi.bmp" } ,
    { "TRIM3_BITMAP" ,           "BITMAP" ,                 "trim3_bi.bmp" } ,
    { "TRIM4_BITMAP" ,           "BITMAP" ,                 "trim4_bi.bmp" } ,
    { "TRIM5_BITMAP" ,           "BITMAP" ,                 "trim5_bi.bmp" } ,
    { "TRIM6_BITMAP" ,           "BITMAP" ,                 "trim6_bi.bmp" } ,
    { "TRIM7_BITMAP" ,           "BITMAP" ,                 "trim7_bi.bmp" } ,
    { "TRIM8_BITMAP" ,           "BITMAP" ,                 "trim8_bi.bmp" } ,
    { "TRIM9_BITMAP" ,           "BITMAP" ,                 "trim9_bi.bmp" } ,
    { "UNDO_BITMAP" ,            "BITMAP" ,                 "undo_bit.bmp" } ,
    { "VIEW1_BITMAP" ,           "BITMAP" ,                 "view1_bi.bmp" } ,
    { "VIEW10_BITMAP" ,          "BITMAP" ,                 "view10_b.bmp" } ,
    { "VIEW11_BITMAP" ,          "BITMAP" ,                 "view11_b.bmp" } ,
    { "VIEW12_BITMAP" ,          "BITMAP" ,                 "view12_b.bmp" } ,
    { "VIEW14_BITMAP" ,          "BITMAP" ,                 "view14_b.bmp" } ,
    { "VIEW2_BITMAP" ,           "BITMAP" ,                 "view2_bi.bmp" } ,
    { "VIEW3_BITMAP" ,           "BITMAP" ,                 "view3_bi.bmp" } ,
    { "VIEW4_BITMAP" ,           "BITMAP" ,                 "view4_bi.bmp" } ,
    { "VIEW5_BITMAP" ,           "BITMAP" ,                 "view5_bi.bmp" } ,
    { "VIEW6_BITMAP" ,           "BITMAP" ,                 "view6_bi.bmp" } ,
    { "VIEW7_BITMAP" ,           "BITMAP" ,                 "view7_bi.bmp" } ,
    { "VIEW8_BITMAP" ,           "BITMAP" ,                 "view8_bi.bmp" } ,
    { "VIEW9_BITMAP" ,           "BITMAP" ,                 "view9_bi.bmp" } ,
    { "VIEWBACK_BITMAP" ,        "BITMAP" ,                 "viewback.bmp" } ,
    { "VIEWBOTTOM_BITMAP" ,      "BITMAP" ,                 "viewbott.bmp" } ,
    { "VIEWFRONT_BITMAP" ,       "BITMAP" ,                 "viewfron.bmp" } ,
    { "VIEWISO_BITMAP" ,         "BITMAP" ,                 "viewiso_.bmp" } ,
    { "VIEWLEFT_BITMAP" ,        "BITMAP" ,                 "viewleft.bmp" } ,
    { "VIEWPAR_BITMAP" ,         "BITMAP" ,                 "viewpar_.bmp" } ,
    { "VIEWPERSP_BITMAP" ,       "BITMAP" ,                 "viewpers.bmp" } ,
    { "VIEWRIGHT_BITMAP" ,       "BITMAP" ,                 "viewrigh.bmp" } ,
    { "VIEWTOP_BITMAP" ,         "BITMAP" ,                 "viewtop_.bmp" } ,
    { "WEIGHT_BITMAP" ,          "BITMAP" ,                 "weight_b.bmp" } ,
    { "YZ1_BITMAP" ,             "BITMAP" ,                 "yz1_bitm.bmp" } ,
    { "YZ2_BITMAP" ,             "BITMAP" ,                 "yz2_bitm.bmp" } ,
    { "YZ3_BITMAP" ,             "BITMAP" ,                 "yz3_bitm.bmp" } ,
    { "YZ4_BITMAP" ,             "BITMAP" ,                 "yz4_bitm.bmp" } ,
    { "YZ5_BITMAP" ,             "BITMAP" ,                 "yz5_bitm.bmp" } ,
    { "YZ6_BITMAP" ,             "BITMAP" ,                 "yz6_bitm.bmp" } ,
    { "YZ7_BITMAP" ,             "BITMAP" ,                 "yz7_bitm.bmp" } ,
    { "YZ8_BITMAP" ,             "BITMAP" ,                 "yz8_bitm.bmp" } ,
    { "YZ9_BITMAP" ,             "BITMAP" ,                 "yz9_bitm.bmp" } ,
    { "ZOOM0_BITMAP" ,           "BITMAP" ,                 "zoom0_bi.bmp" } ,
    { "ZOOM1_BITMAP" ,           "BITMAP" ,                 "zoom1_bi.bmp" } ,
    { "ZOOM2_BITMAP" ,           "BITMAP" ,                 "zoom2_bi.bmp" } ,
    { "ZOOM3_BITMAP" ,           "BITMAP" ,                 "zoom3_bi.bmp" } ,
    { "ZOOM4_BITMAP" ,           "BITMAP" ,                 "zoom4_bi.bmp" } ,
    { "ZOOM5_BITMAP" ,           "BITMAP" ,                 "zoom5_bi.bmp" } ,
    { "ZOOM6_BITMAP" ,           "BITMAP" ,                 "zoom6_bi.bmp" } ,
    { "ZOOM7_BITMAP" ,           "BITMAP" ,                 "zoom7_bi.bmp" } ,
    { "ZOOM8_BITMAP" ,           "BITMAP" ,                 "zoom8_bi.bmp" } ,
    { "ARTABLE_BITMAP" ,         "BITMAP" ,                 "artable_.bmp" } ,
    { "ARNUMBER_BITMAP" ,        "BITMAP" ,                 "arnumber.bmp" } ,
    { "ARNOTATIONOPTIONS_BITMAP" ,"BITMAP" ,                 "bmp00023.bmp" } ,
    { "ARLAYER_BITMAP" ,         "BITMAP" ,                 "arlayer_.bmp" } ,
    { "ARJOIN_BITMAP" ,          "BITMAP" ,                 "arjoin_b.bmp" } ,
    { "ARDIMENSION_BITMAP" ,     "BITMAP" ,                 "ardimens.bmp" } ,
    { "ARCOLUMNGRID_BITMAP" ,    "BITMAP" ,                 "arcolumn.bmp" } ,
    { "ARCOLUMNDEFAULTS_BITMAP" ,"BITMAP" ,                 "bmp00024.bmp" } ,
    { "ARCOLUMN_BITMAP" ,        "BITMAP" ,                 "bmp00025.bmp" } ,
    { "ANIMATION9_BITMAP" ,      "BITMAP" ,                 "animatio.bmp" } ,
    { "ANIMATION8_BITMAP" ,      "BITMAP" ,                 "bmp00026.bmp" } ,
    { "ANIMATION7_BITMAP" ,      "BITMAP" ,                 "bmp00027.bmp" } ,
    { "ANIMATION6_BITMAP" ,      "BITMAP" ,                 "bmp00028.bmp" } ,
    { "ANIMATION5_BITMAP" ,      "BITMAP" ,                 "bmp00029.bmp" } ,
    { "ANIMATION4_BITMAP" ,      "BITMAP" ,                 "bmp00030.bmp" } ,
    { "ANIMATION3_BITMAP" ,      "BITMAP" ,                 "bmp00031.bmp" } ,
    { "ANIMATION2_BITMAP" ,      "BITMAP" ,                 "bmp00032.bmp" } ,
    { "ANIMATION1_BITMAP" ,      "BITMAP" ,                 "bmp00033.bmp" } ,
    { "ANIMATION12_BITMAP" ,     "BITMAP" ,                 "bmp00034.bmp" } ,
    { "ANIMATION11_BITMAP" ,     "BITMAP" ,                 "bmp00035.bmp" } ,
    { "ANIMATION10_BITMAP" ,     "BITMAP" ,                 "bmp00036.bmp" } ,
    { "SURFACE7_BITMAP" ,        "BITMAP" ,                 "surface7.bmp" } ,
    { "DIMEN11_BITMAP" ,         "BITMAP" ,                 "dimen11_.bmp" } ,
    { "RAYTRACE1_BITMAP" ,       "BITMAP" ,                 "raytrace.bmp" } ,
    { "RAYTRACE2_BITMAP" ,       "BITMAP" ,                 "bmp00037.bmp" } ,
    { "RAYTRACE3_BITMAP" ,       "BITMAP" ,                 "bmp00038.bmp" } ,
    { "RAYTRACE4_BITMAP" ,       "BITMAP" ,                 "bmp00039.bmp" } ,
    { "STYLESET_BITMAP" ,        "BITMAP" ,                 "styleset.bmp" } ,
    { "ARTRUSS_BITMAP" ,         "BITMAP" ,                 "artruss_.bmp" } ,
    { "ARFRAME_BITMAP" ,         "BITMAP" ,                 "arframe_.bmp" } ,
    { "SURFACE8_BITMAP" ,        "BITMAP" ,                 "surface8.bmp" } ,
    { "VIEWBACKRESET_BITMAP" ,   "BITMAP" ,                 "bmp00040.bmp" } ,
    { "VIEWBOTTOMRESET_BITMAP" , "BITMAP" ,                 "bmp00041.bmp" } ,
    { "VIEWFRONTRESET_BITMAP" ,  "BITMAP" ,                 "bmp00042.bmp" } ,
    { "VIEWISORESET_BITMAP" ,    "BITMAP" ,                 "viewisor.bmp" } ,
    { "VIEWLEFTRESET_BITMAP" ,   "BITMAP" ,                 "bmp00043.bmp" } ,
    { "VIEWPARRESET_BITMAP" ,    "BITMAP" ,                 "viewparr.bmp" } ,
    { "VIEWPERSPRESET_BITMAP" ,  "BITMAP" ,                 "bmp00044.bmp" } ,
    { "VIEWRIGHTRESET_BITMAP" ,  "BITMAP" ,                 "bmp00045.bmp" } ,
    { "VIEWTOPRESET_BITMAP" ,    "BITMAP" ,                 "viewtopr.bmp" } ,
    { "ARJOBINFO_BITMAP" ,       "BITMAP" ,                 "arjobinf.bmp" } ,
    { "ARNEWDRAWING_BITMAP" ,    "BITMAP" ,                 "arnewdra.bmp" } ,
    { "ARLAYERS_BITMAP" ,        "BITMAP" ,                 "arlayers.bmp" } ,
    { "ARCHAMFER_BITMAP" ,       "BITMAP" ,                 "archamfe.bmp" } ,
    { "ARDIVIDEWALL_BITMAP" ,    "BITMAP" ,                 "ardivide.bmp" } ,
    { "ARTRIMINTERSECTION_BITMAP" ,"BITMAP" ,                 "artrimin.bmp" } ,
    { "ARFRAMEALLOWANCE_BITMAP" ,"BITMAP" ,                 "arframea.bmp" } ,
    { "ARPRINT_BITMAP" ,         "BITMAP" ,                 "arprint_.bmp" } ,
    { "ARBAYWINDOW_BITMAP" ,     "BITMAP" ,                 "arbaywin.bmp" } ,
    { "TEXT5_BITMAP" ,           "BITMAP" ,                 "text5_bi.bmp" } ,
    { "FIGURE5_BITMAP" ,         "BITMAP" ,                 "figure5_.bmp" } ,
    { "TEXT6_BITMAP" ,           "BITMAP" ,                 "text6_bi.bmp" } ,
    { "POSITION8_BITMAP" ,       "BITMAP" ,                 "bmp00046.bmp" } ,
    { "POSITION9_BITMAP" ,       "BITMAP" ,                 "bmp00047.bmp" } ,
    { "CA_ANIMATION1_BITMAP" ,   "BITMAP" ,                 "animation-camera-path.svg" } ,
    { "CA_ANIMATION2_BITMAP" ,   "BITMAP" ,                 "animation-reference-path.svg" } ,
    { "CA_ANIMATION3_BITMAP" ,   "BITMAP" ,                 "animation-object-path.svg" } ,
    { "CA_ANIMATION4_BITMAP" ,   "BITMAP" ,                 "animation-record-animation.svg" } ,
    { "CA_ANIMATION5_BITMAP" ,   "BITMAP" ,                 "animation-replay-animation.svg" } ,
    { "CA_ANIMATION12_BITMAP" ,  "BITMAP" ,                 "animation-patch-path.svg" } ,
    { "CA_ANIMATION8_BITMAP" ,   "BITMAP" ,                 "bmp00053.bmp" } ,
    { "POSITION10_BITMAP" ,      "BITMAP" ,                 "bmp00054.bmp" } ,
    { "COMPOSE9_BITMAP" ,        "BITMAP" ,                 "compose9.bmp" } ,
    { "SURFACE9_BITMAP" ,        "BITMAP" ,                 "fill-hole.svg" } ,
    { "POSITION11_BITMAP" ,      "BITMAP" ,                 "locate-xyz-reference.svg" } ,
    { "PANEL1_BITMAP" ,          "BITMAP" ,                 "bmp00190.bmp" } ,
    { "NC7_BITMAP" ,             "BITMAP" ,                 "bmp00191.bmp" } ,
    { "POLYGON0_IN_BITMAP" ,     "BITMAP" ,                 "Polygon0_in.bmp" } ,
    { "POLYGON0_OUT_BITMAP" ,    "BITMAP" ,                 "Polygon0_out.bmp" } ,
    { "POLYGON1_IN_BITMAP" ,     "BITMAP" ,                 "Polygon1_in.bmp" } ,
    { "POLYGON1_OUT_BITMAP" ,    "BITMAP" ,                 "Polygon1_out.bmp" } ,
    { "CA_CIRCLE0_BITMAP" ,      "BITMAP" ,                 "circles-commands.svg" } ,
    { "CA_CIRCLE1_BITMAP" ,      "BITMAP" ,                 "circle-by-center-and-circumference.svg" } ,
    { "CA_CIRCLE2_BITMAP" ,      "BITMAP" ,                 "circle-fixed-value-circle.svg" } ,
    { "CA_CIRCLE3_BITMAP" ,      "BITMAP" ,                 "circle-by-three-circumference-points.svg" } ,
    { "CA_CIRCLE4_BITMAP" ,      "BITMAP" ,                 "circle-by-two-circumference-points.svg" } ,
    { "CA_ARC1_BITMAP" ,         "BITMAP" ,                 "circle-arc-by-center-and-circumference.svg" } ,
    { "CA_ARC2_BITMAP" ,         "BITMAP" ,                 "circle-fixed-value-arc.svg" } ,
    { "CA_ARC0_BITMAP" ,         "BITMAP" ,                 "circle-fixed-value-arc.svg" } ,
    { "CA_ARC3_BITMAP" ,         "BITMAP" ,                 "circle-arc-by-three-points.svg" } ,
    { "CA_ARC4_BITMAP" ,         "BITMAP" ,                 "circle-fillet-arc.svg" } ,
    { "CA_ELLIPSE1_BITMAP" ,     "BITMAP" ,                 "circle-ellipse-by-three-points.svg" } ,
    { "CA_ELLIPSE2_BITMAP" ,     "BITMAP" ,                 "circle-fixed-value-ellipse.svg" } ,
    { "CA_POINT0_BITMAP" ,       "BITMAP" ,                 "point-commands.svg"} ,
    { "CA_POINT1_BITMAP" ,       "BITMAP" ,                 "points-single-point.svg" } ,
    { "CA_POINT2_BITMAP" ,       "BITMAP" ,                 "points-generate-points.svg" } ,
    { "CA_LINE0_BITMAP" ,        "BITMAP" ,                 "lines-commands.svg" } ,
    { "CA_LINE1_BITMAP" ,        "BITMAP" ,                 "lines.svg" } ,
    { "CA_LINE2_BITMAP" ,        "BITMAP" ,                 "lines-x-axis-line.svg" } ,
    { "CA_LINE3_BITMAP" ,        "BITMAP" ,                 "lines-y-axis-line.svg" } ,
    { "CA_LINE4_BITMAP" ,        "BITMAP" ,                 "lines-angled-line.svg" } ,
    { "CA_LINE5_BITMAP" ,        "BITMAP" ,                 "lines-chamfer.svg" } ,
    { "CA_LINE6_BITMAP" ,        "BITMAP" ,                 "lines-multiple-lines.svg" } ,
    { "CA_LINE7_BITMAP" ,        "BITMAP" ,                 "lines-rectangle.svg" } ,
    { "CA_LINE8_BITMAP" ,        "BITMAP" ,                 "lines-regular-polygon.svg" } ,
    { "CA_CURVE0_BITMAP" ,       "BITMAP" ,                 "curve.svg" } ,
    { "CA_CURVE1_BITMAP" ,       "BITMAP" ,                 "curve-by-control-points.svg" } ,
    { "CA_CURVE2_BITMAP" ,       "BITMAP" ,                 "curve-move-control-point.svg" } ,
    { "CA_CURVE3_BITMAP" ,       "BITMAP" ,                 "curve-change-degree.svg" } ,
    { "CA_CURVE4_BITMAP" ,       "BITMAP" ,                 "curve-thru-points.svg" } ,
    { "CA_CURVE5_BITMAP" ,       "BITMAP" ,                 "curve-add-control-point.svg" } ,
    { "CA_CURVE6_BITMAP" ,       "BITMAP" ,                 "convert-to-curves.svg" } ,
    { "CA_PLANE0_BITMAP" ,       "BITMAP" ,                 "planes.svg" } ,
    { "CA_PLANE1_BITMAP" ,       "BITMAP" ,                 "plane-by-boundary.svg" } ,
    { "CA_PLANE3_BITMAP" ,       "BITMAP" ,                 "plane-by-interior-position.svg" } ,
    { "CA_PLANE2_BITMAP" ,       "BITMAP" ,                 "plane-by-vertex-points.svg" } ,
    { "CA_PLANE4_BITMAP" ,       "BITMAP" ,                 "plane-add-vertex.svg" } ,
    { "CA_PLANE5_BITMAP" ,       "BITMAP" ,                 "plane-delete-vertex.svg" } ,
    { "CA_PLANE6_BITMAP" ,       "BITMAP" ,                 "plane-move-vertex.svg" } ,
    { "CA_PLANE7_BITMAP" ,       "BITMAP" ,                 "plane-whiteout.svg" } ,
    { "CA_SURFACE0_BITMAP" ,     "BITMAP" ,                 "surfaces.svg" } ,
    { "CA_SURFACE2_BITMAP" ,     "BITMAP" ,                 "surfaces-ruled-surface.svg" } ,
    { "CA_SURFACE3_BITMAP" ,     "BITMAP" ,                 "surfaces-cylinder.svg" } ,
    { "CA_SURFACE4_BITMAP" ,     "BITMAP" ,                 "surfaces-revolve-surface.svg" } ,
    { "CA_SURFACE5_BITMAP" ,     "BITMAP" ,                 "surfaces-elbow.svg" } ,
    { "CA_SURFACE6_BITMAP" ,     "BITMAP" ,                 "surfaces-unfold.svg" } ,
    { "CA_SURFACE7_BITMAP" ,     "BITMAP" ,                 "surfaces-spiral.svg" } ,
    { "CA_PATCH1_BITMAP" ,       "BITMAP" ,                 "surfaces-patch-by-mesh.svg" } ,
    { "CA_PATCH2_BITMAP" ,       "BITMAP" ,                 "surfaces-patch-by-corners.svg" } ,
    { "CA_PATCH3_BITMAP" ,       "BITMAP" ,                 "surfaces-move-patch-points.svg" } ,
    { "CA_TEXT0_BITMAP" ,        "BITMAP" ,                 "text-commands.svg" } ,
    { "CA_TEXT1_BITMAP" ,        "BITMAP" ,                 "text-by-origin.svg" } ,
    { "CA_TEXT2_BITMAP" ,        "BITMAP" ,                 "text-edit-text.svg" } ,
    { "CA_TEXT3_BITMAP" ,        "BITMAP" ,                 "component-annotation-text.svg" } ,
    { "CA_TEXT4_BITMAP" ,        "BITMAP" ,                 "component-edit-annotation-text.svg" } ,
    { "CA_TEXT5_BITMAP" ,        "BITMAP" ,                 "text-incremental-text.svg" } ,
    { "CA_TEXT6_BITMAP" ,        "BITMAP" ,                 "text-by-two-points.svg" } ,
    { "CA_TEXT7_BITMAP" ,        "BITMAP" ,                 "text-along-an-entity.svg" } ,
    { "CA_FIGURE0_BITMAP" ,      "BITMAP" ,                 "components-commands.svg" } ,
    { "CA_FIGURE1_BITMAP" ,      "BITMAP" ,                 "component-by-origin.svg" } ,
    { "CA_FIGURE2_BITMAP" ,      "BITMAP" ,                 "component-by-two-points.svg" } ,
    { "CA_FIGURE3_BITMAP" ,      "BITMAP" ,                 "component-by-three-points.svg" } ,
    { "CA_FIGURE4_BITMAP" ,      "BITMAP" ,                 "component-create-from-selection.svg" } ,
    { "CA_FIGURE5_BITMAP" ,      "BITMAP" ,                 "component-dynamic-scale.svg" } ,
    { "CA_GROUP0_BITMAP" ,       "BITMAP" ,                 "group-commands.svg" } ,
    { "CA_GROUP1_BITMAP" ,       "BITMAP" ,                 "group-create-new.svg" } ,
    { "CA_GROUP2_BITMAP" ,       "BITMAP" ,                 "group-remove-from-group.svg" } ,
    { "CA_GROUP3_BITMAP" ,       "BITMAP" ,                 "group-add-to-group.svg" } ,
    { "CA_GROUP4_BITMAP" ,       "BITMAP" ,                 "group-ungroup.svg" } ,
    { "CA_BITMAP0_BITMAP" ,      "BITMAP" ,                 "images-commands.svg" } ,
    { "CA_BITMAP1_BITMAP" ,      "BITMAP" ,                 "image-by-fixed-size.svg" } ,
    { "CA_BITMAP2_BITMAP" ,      "BITMAP" ,                 "image-by-two-points.svg" } ,
    { "CA_DIMEN0_BITMAP" ,       "BITMAP" ,                 "dimension-commands.svg" } ,
    { "CA_DIMEN1_BITMAP" ,       "BITMAP" ,                 "dimension-x-axis.svg" } ,
    { "CA_DIMEN2_BITMAP" ,       "BITMAP" ,                 "dimension-y-axis.svg" } ,
    { "CA_DIMEN3_BITMAP" ,       "BITMAP" ,                 "dimension-angle.svg" } ,
    { "CA_DIMEN4_BITMAP" ,       "BITMAP" ,                 "dimension-distance-and-bearing.svg" } ,
    { "CA_DIMEN5_BITMAP" ,       "BITMAP" ,                 "dimension-radius-with-leader.svg" } ,
    { "CA_DIMEN6_BITMAP" ,       "BITMAP" ,                 "dimension-diameter-with-leader.svg" } ,
    { "CA_DIMEN7_BITMAP" ,       "BITMAP" ,                 "dimension-diameter.svg" } ,
    { "CA_DIMEN8_BITMAP" ,       "BITMAP" ,                 "dimension-parallel.svg" } ,
    { "CA_DIMEN9_BITMAP" ,       "BITMAP" ,                 "dimension-radius.svg" } ,
    { "CA_DIMEN10_BITMAP" ,      "BITMAP" ,                 "text-label-callout-leader" } ,
    { "CA_DIMEN11_BITMAP" ,      "BITMAP" ,                 "dimension-move-dimension-text.svg" } ,
    { "CA_TRIM1_BITMAP" ,        "BITMAP" ,                 "edit-trim-to-position.svg" } ,
    { "CA_TRIM2_BITMAP" ,        "BITMAP" ,                 "edit-trim-by-or-to-value.svg" } ,
    { "CA_TRIM3_BITMAP" ,        "BITMAP" ,                 "edit-divide-by-entity.svg" } ,
    { "CA_TRIM5_BITMAP" ,        "BITMAP" ,                 "edit-divide-by-number.svg" } ,
    { "CA_TRIM4_BITMAP" ,        "BITMAP" ,                 "edit-trim-by-length.svg" } ,
    { "CA_TRIM6_BITMAP" ,        "BITMAP" ,                 "ca_trim6.bmp" } ,
    { "CA_TRIM7_BITMAP" ,        "BITMAP" ,                 "ca_trim7.bmp" } ,
    { "CA_TRIM8_BITMAP" ,        "BITMAP" ,                 "edit-remove-segment.svg" } ,
    { "CA_TRIM9_BITMAP" ,        "BITMAP" ,                 "edit-explode.svg" } ,
    { "CA_TRIM10_BITMAP" ,       "BITMAP" ,                 "edit-trim-to-corner.svg" } ,
    { "CA_TRIM11_BITMAP" ,       "BITMAP" ,                 "bmp00098.bmp" } ,
    { "CA_MEASURE0_BITMAP" ,     "BITMAP" ,                 "measure.svg" } ,
    { "CA_MEASURE1_BITMAP" ,     "BITMAP" ,                 "bmp00099.bmp" } ,
    { "CA_MEASURE2_BITMAP" ,     "BITMAP" ,                 "bmp00100.bmp" } ,
    { "CA_MEASURE3_BITMAP" ,     "BITMAP" ,                 "bmp00101.bmp" } ,
    { "CA_ENTITY_BITMAP" ,       "BITMAP" ,                 "visibility-entity-display.svg" } ,
    { "CA_COLOUR_BITMAP" ,       "BITMAP" ,                 "colour.svg" } ,
    { "CA_LAYER_BITMAP" ,        "BITMAP" ,                 "layer.svg" } ,
    { "CA_WEIGHT_BITMAP" ,       "BITMAP" ,                 "weight.svg" } ,
    { "CA_STYLE_BITMAP" ,        "BITMAP" ,                 "style.svg" } ,
    { "CA_STYLESET_BITMAP" ,     "BITMAP" ,                 "style-sets.svg" } ,
    { "CA_UNDO_BITMAP" ,         "BITMAP" ,                 "undo.svg" } ,
    { "CA_REDO_BITMAP" ,         "BITMAP" ,                 "redo.svg" } ,
    { "CA_ZOOM0_BITMAP" ,        "BITMAP" ,                 "zoom-commands.svg" } ,
    { "CA_ZOOM2_BITMAP" ,        "BITMAP" ,                 "zoom-pan-scroll.svg" } ,
    { "CA_ZOOM3_BITMAP" ,        "BITMAP" ,                 "zoom-in.svg" } ,
    { "CA_ZOOM4_BITMAP" ,        "BITMAP" ,                 "zoom-out.svg" } ,
    { "CA_ZOOM5_BITMAP" ,        "BITMAP" ,                 "zoom-scale.svg" } ,
    { "CA_ZOOM6_BITMAP" ,        "BITMAP" ,                 "zoom-fit.svg" } ,
    { "CA_ZOOM7_BITMAP" ,        "BITMAP" ,                 "zoom-previous.svg" } ,
    { "CA_ZOOM8_BITMAP" ,        "BITMAP" ,                 "zoom-to-zone.svg" } ,
    { "CA_ZOOM1_BITMAP" ,        "BITMAP" ,                 "zoom-window.svg" } ,
    { "CA_PAINT0_BITMAP" ,       "BITMAP" ,                 "view-regenerate-view.svg" } ,
    { "CA_VIEWBACK_BITMAP" ,     "BITMAP" ,                 "ca_viewb.bmp" } ,
    { "CA_VIEWBOTTOM_BITMAP" ,   "BITMAP" ,                 "bmp00103.bmp" } ,
    { "CA_VIEWFRONT_BITMAP" ,    "BITMAP" ,                 "ca_viewf.bmp" } ,
    { "CA_VIEWISO_BITMAP" ,      "BITMAP" ,                 "ca_viewi.bmp" } ,
    { "CA_VIEWLEFT_BITMAP" ,     "BITMAP" ,                 "ca_viewl.bmp" } ,
    { "CA_VIEWPAR_BITMAP" ,      "BITMAP" ,                 "ca_viewp.bmp" } ,
    { "CA_VIEWPERSP_BITMAP" ,    "BITMAP" ,                 "bmp00104.bmp" } ,
    { "CA_VIEWRIGHT_BITMAP" ,    "BITMAP" ,                 "ca_viewr.bmp" } ,
    { "CA_VIEWTOP_BITMAP" ,      "BITMAP" ,                 "ca_viewt.bmp" } ,
    { "CA_POSITION0_BITMAP" ,    "BITMAP" ,                 "locate-commands.svg" } ,
    { "CA_CREATEWINDOW_BITMAP" , "BITMAP" ,                 "ca_creat.bmp" } ,
    { "CA_RESETWINDOW_BITMAP" ,  "BITMAP" ,                 "ca_reset.bmp" } ,
    { "CA_TRIM0_BITMAP" ,        "BITMAP" ,                 "edit-commands.svg" } ,
    { "CA_POSITION1_BITMAP" ,    "BITMAP" ,                 "locate-reference-point.svg" } ,
    { "CA_POSITION2_BITMAP" ,    "BITMAP" ,                 "locate-on.svg" } ,
    { "CA_POSITION3_BITMAP" ,    "BITMAP" ,                 "locate-along.svg" } ,
    { "CA_POSITION4_BITMAP" ,    "BITMAP" ,                 "locate-origin-midpoint.svg" } ,
    { "CA_POSITION5_BITMAP" ,    "BITMAP" ,                 "locate-end.svg" } ,
    { "CA_POSITION6_BITMAP" ,    "BITMAP" ,                 "selectability-chain-selection.svg" } ,
    { "CA_POSITION7_BITMAP" ,    "BITMAP" ,                 "locate-intersection.svg" } ,
    { "CA_RAYTRACE2_BITMAP" ,    "BITMAP" ,                 "ca_raytr.bmp" } ,
    { "CA_RAYTRACE1_BITMAP" ,    "BITMAP" ,                 "bmp00112.bmp" } ,
    { "CA_RAYTRACE4_BITMAP" ,    "BITMAP" ,                 "bmp00113.bmp" } ,
    { "CA_RAYTRACE3_BITMAP" ,    "BITMAP" ,                 "bmp00114.bmp" } ,
    { "CA_SELECTIONMASK0_BITMAP" ,"BITMAP" ,                "selectability-commands.svg" } ,
    { "CA_DISPLAYMASK0_BITMAP" , "BITMAP" ,                 "visibility.svg" } ,
    { "CA_MASK4_BITMAP" ,        "BITMAP" ,                 "selectability-style-selection.svg" } ,
    { "CA_MASK2_BITMAP" ,        "BITMAP" ,                 "selectability-colour-selection.svg" } ,
    { "CA_MASK3_BITMAP" ,        "BITMAP" ,                 "selectability-layer-selection.svg" } ,
    { "CA_MASK5_BITMAP" ,        "BITMAP" ,                 "selectability-weight-selection.svg" } ,
    { "CA_COMPOSE4_BITMAP" ,     "BITMAP" ,                 "ca_compo.bmp" } ,
    { "CA_COMPOSE0_BITMAP" ,     "BITMAP" ,                 "layout-commands.svg" } ,
    { "CA_COMPOSE5_BITMAP" ,     "BITMAP" ,                 "layout-delete-view.svg" } ,
    { "CA_COMPOSE2_BITMAP" ,     "BITMAP" ,                 "layout-delete.svg" } ,
    { "CA_COMPOSE6_BITMAP" ,     "BITMAP" ,                 "layout-pan-view.svg" } ,
    { "CA_COMPOSE7_BITMAP" ,     "BITMAP" ,                 "layout-zoom-fit-view.svg" } ,
    { "CA_COMPOSE3_BITMAP" ,     "BITMAP" ,                 "layout-add-view.svg" } ,
    { "CA_COMPOSE1_BITMAP" ,     "BITMAP" ,                 "layout-new-layout.svg" } ,
    { "CA_COMPOSE8_BITMAP" ,     "BITMAP" ,                 "layout-select-layout.svg" } ,
    { "CA_COMPOSE9_BITMAP" ,     "BITMAP" ,                 "layout-move-view.svg" } ,
    { "CA_POSITION8_BITMAP" ,    "BITMAP" ,                 "locate-offset-point.svg" } ,
    { "COMPOSE10_BITMAP" ,       "BITMAP" ,                 "viewport-align.svg" } ,
    { "TRANSFORM1_BITMAP" ,      "BITMAP" ,                 "transfor.bmp" } ,
    { "TRANSFORM2_BITMAP" ,      "BITMAP" ,                 "bmp00124.bmp" } ,
    { "TRANSFORM3_BITMAP" ,      "BITMAP" ,                 "bmp00125.bmp" } ,
    { "TRANSFORM4_BITMAP" ,      "BITMAP" ,                 "bmp00126.bmp" } ,
    { "TRANSFORM5_BITMAP" ,      "BITMAP" ,                 "bmp00127.bmp" } ,
    { "TRANSFORM6_BITMAP" ,      "BITMAP" ,                 "bmp00128.bmp" } ,
    { "TRANSFORM7_BITMAP" ,      "BITMAP" ,                 "bmp00129.bmp" } ,
    { "TRANSFORM8_BITMAP" ,      "BITMAP" ,                 "bmp00130.bmp" } ,
    { "TRANSFORM9_BITMAP" ,      "BITMAP" ,                 "bmp00131.bmp" } ,
    { "TRANSFORM10_BITMAP" ,     "BITMAP" ,                 "bmp00132.bmp" } ,
    { "TRANSFORM11_BITMAP" ,     "BITMAP" ,                 "bmp00133.bmp" } ,
    { "CA_TRANSFORM1_BITMAP" ,   "BITMAP" ,                 "transform-copy-along.svg" } ,
    { "CA_TRANSFORM2_BITMAP" ,   "BITMAP" ,                 "transform-array.svg" } ,
    { "CA_TRANSFORM3_BITMAP" ,   "BITMAP" ,                 "transform-copy.svg" } ,
    { "CA_TRANSFORM4_BITMAP" ,   "BITMAP" ,                 "transform-mirror.svg" } ,
    { "CA_TRANSFORM5_BITMAP" ,   "BITMAP" ,                 "transform-move.svg" } ,
    { "CA_TRANSFORM6_BITMAP" ,   "BITMAP" ,                 "transform-offset.svg" } ,
    { "CA_TRANSFORM7_BITMAP" ,   "BITMAP" ,                 "offset-equal-distance.svg" } ,
    { "CA_TRANSFORM8_BITMAP" ,   "BITMAP" ,                 "transform-project.svg" } ,
    { "CA_TRANSFORM9_BITMAP" ,   "BITMAP" ,                 "transform-rotate.svg" } ,
    { "CA_TRANSFORM10_BITMAP" ,  "BITMAP" ,                 "transform-scale.svg" } ,
    { "CA_TRANSFORM11_BITMAP" ,  "BITMAP" ,                 "transform-stretch.svg" } ,
    { "TRANSFORM0_BITMAP" ,      "BITMAP" ,                 "bmp00144.bmp" } ,
    { "CA_TRANSFORM0_BITMAP" ,   "BITMAP" ,                 "transform-commands.svg" } ,
    { "CA_DYNAMICVIEW0_BITMAP" , "BITMAP" ,                 "dynamic-view.svg" } ,
    { "CA_DYNAMICVIEW1_BITMAP" , "BITMAP" ,                 "view-fly.svg" } ,
    { "CA_DYNAMICVIEW2_BITMAP" , "BITMAP" ,                 "view-continuous-rotation.svg" } ,
    { "CA_DYNAMICVIEW3_BITMAP" , "BITMAP" ,                 "view-orbit.svg" } ,
    { "CA_DYNAMICVIEW4_BITMAP" , "BITMAP" ,                 "view-walk.svg" } ,
    { "CA_DYNAMICVIEW5_BITMAP" , "BITMAP" ,                 "view-continuous-orbit.svg" } ,
    { "CA_WORKPLANE0_BITMAP" ,   "BITMAP" ,                 "workplane-commands.svg" } ,
    { "CA_WORKPLANE1_BITMAP" ,   "BITMAP" ,                 "workplane-new.svg" } ,
    { "CA_WORKPLANE2_BITMAP" ,   "BITMAP" ,                 "workplane-delete-workplane.svg" } ,
    { "CA_WORKPLANE3_BITMAP" ,   "BITMAP" ,                 "workplane-change-by-three-points.svg" } ,
    { "CA_WORKPLANE4_BITMAP" ,   "BITMAP" ,                 "workplane-move-workplane-origin.svg" } ,
    { "CA_WORKPLANE5_BITMAP" ,   "BITMAP" ,                 "workplane-reset-workplane-to-standard.svg" } ,
    { "CA_POSITION9_BITMAP" ,    "BITMAP" ,                 "locate-apparent-intersection.svg" } ,
    { "CA_ZOOM9_BITMAP" ,        "BITMAP" ,                 "view-regenerate-view.svg" } ,
    { "COMPOSE8_BITMAP" ,        "BITMAP" ,                 "compose8.bmp" } ,
    { "CA_MASK1_BITMAP" ,        "BITMAP" ,                 "selectability-entity-selection.svg" } ,
    { "CA_WORKPLANE6_BITMAP" ,   "BITMAP" ,                 "workplane-select.svg" } ,
    { "CA_WORKPLANE7_BITMAP" ,   "BITMAP" ,                 "workplane-grid-settings.svg" } ,
    { "CA_VIEWMENU0_BITMAP" ,    "BITMAP" ,                 "view-commands.svg" } ,
    { "CA_VIEWMENU1_BITMAP" ,    "BITMAP" ,                 "view-select-view.svg" } ,
    { "CA_VIEWMENU2_BITMAP" ,    "BITMAP" ,                 "view-new-view.svg" } ,
    { "CA_VIEWMENU6_BITMAP" ,    "BITMAP" ,                 "zoom-delete-zone.svg" } ,
    { "CA_VIEWMENU3_BITMAP" ,    "BITMAP" ,                 "layout-delete-view.svg" } ,
    { "CA_VIEWMENU5_BITMAP" ,    "BITMAP" ,                 "zoom-create-zone.svg" } ,
    { "CA_VIEWMENU4_BITMAP" ,    "BITMAP" ,                 "view-plot-scale.svg" } ,
    { "CA_DYNAMICVIEW6_BITMAP" , "BITMAP" ,                 "architectural-perspective.svg" } ,
    { "CA_DYNAMICVIEW7_BITMAP" , "BITMAP" ,                 "view-adjust-menu.svg" } ,
    { "CA_DYNAMICVIEW9_BITMAP" , "BITMAP" ,                 "align-to-workplane.svg" } ,
    { "CA_DYNAMICVIEW8_BITMAP" , "BITMAP" ,                 "view-rotate.svg" } ,
    { "CA_DYNAMICVIEW10_BITMAP" ,"BITMAP" ,                 "view-reset-view-to-standard.svg" } ,
    { "CA_RENDER1_BITMAP" ,      "BITMAP" ,                 "hidden-line.svg" } ,
    { "CA_RENDER2_BITMAP" ,      "BITMAP" ,                 "bmp00171.bmp" } ,
    { "CA_RENDER3_BITMAP" ,      "BITMAP" ,                 "shaded.svg" } ,
    { "CA_RENDER4_BITMAP" ,      "BITMAP" ,                 "view-regenerate-view.svg" } ,
    { "CA_RENDER7_BITMAP" ,      "BITMAP" ,                 "rendering-lights.svg" } ,
    { "CA_RENDER8_BITMAP" ,      "BITMAP" ,                 "render-render.svg" } ,
    { "CA_DELETE_BITMAP" ,       "BITMAP" ,                 "delete.svg" } ,
    { "CA_CLONE_BITMAP" ,        "BITMAP" ,                 "properties-picker.svg" } ,
    { "CA_RENDER0_BITMAP" ,      "BITMAP" ,                 "rendering.svg" } ,
    { "CA_RENDER6_BITMAP" ,      "BITMAP" ,                 "rendering-materials.svg" } ,
    { "CA_RENDER5_BITMAP" ,      "BITMAP" ,                 "rendering-lights.svg" } ,
    { "CLONE_BITMAP" ,           "BITMAP" ,                 "clone_bi.bmp" } ,
    { "CA_POSITION10_BITMAP" ,   "BITMAP" ,                 "selectability-fence-selection.svg" } ,
    { "WORKPLANE0_BITMAP" ,      "BITMAP" ,                 "workplan.bmp" } ,
    { "WORKPLANE1_BITMAP" ,      "BITMAP" ,                 "bmp00180.bmp" } ,
    { "WORKPLANE2_BITMAP" ,      "BITMAP" ,                 "bmp00181.bmp" } ,
    { "WORKPLANE3_BITMAP" ,      "BITMAP" ,                 "bmp00182.bmp" } ,
    { "WORKPLANE4_BITMAP" ,      "BITMAP" ,                 "bmp00183.bmp" } ,
    { "WORKPLANE5_BITMAP" ,      "BITMAP" ,                 "bmp00184.bmp" } ,
    { "WORKPLANE6_BITMAP" ,      "BITMAP" ,                 "bmp00185.bmp" } ,
    { "WORKPLANE7_BITMAP" ,      "BITMAP" ,                 "bmp00186.bmp" } ,
    { "CA_WORKPLANE8_BITMAP" ,   "BITMAP" ,                 "workplane-set-workplane-on-entity.svg" } ,
    { "COMPOSE0_BITMAP" ,        "BITMAP" ,                 "compose0.bmp" } ,
    { "CA_SOLID0_BITMAP" ,       "BITMAP" ,                 "solids.svg" } ,
    { "SAVE_BITMAP" ,            "BITMAP" ,                 "save.svg" } ,
    { "SAVEASEXPORT_BITMAP" ,    "BITMAP" ,                 "save-as.svg" } ,
    { "OPENIMPORT_BITMAP" ,      "BITMAP" ,                 "open-import.svg" } ,
    { "PRINT_BITMAP" ,           "BITMAP" ,                 "print.svg" } ,
    { "PRINTWINDOW_BITMAP" ,     "BITMAP" ,                 "print-preview-window.svg" } ,
    { "PRINTSELECTION_BITMAP" ,  "BITMAP" ,                 "print-preview-selection.svg" } ,
    { "" , "BITMAP" , "" } // last item
};
static int RC_NUM_NAMED_BITMAP_RESOURCES = sizeof(RCnamedBitmapResources)/sizeof(RCnamedResourceImages);

static RCnamedResourceImages RCnamedIconResources [] = {
    { "IDI_ICON1" , "ICON" , "ico1002.ico"  } ,
    { "" , "ICON" , "" } // last item
};
static int RC_NUM_NAMED_ICON_RESOURCES = sizeof(RCnamedIconResources)/sizeof(RCnamedResourceImages);

static RCnumberedResourceImages RCnumberedIconResources [] = {
    { 20001 ,     "ICON" , "padlock-unlock.svg" } ,// unlocked padlock icon
    { 20000 ,     "ICON" , "padlock-lock.svg" } ,// locked padlock icon
    { 1003 ,      "ICON" , "ico1003.ico"  } ,
    { 0 , "ICON" , "" } // last item
};
static int RC_NUM_NUMBERED_ICON_RESOURCES = sizeof(RCnumberedIconResources)/sizeof(RCnumberedResourceImages);

static RCnamedResourceImages RCnamedCursorResources [] = {
    { "EMPTY_CURSOR" ,                      "CURSOR" , ":/images/empty_cur.bmp" } ,
    { "REVEMPTY_CURSOR" ,                   "CURSOR" , ":/images/empty_rev_cur.bmp" } ,
    { "CROSSHAIR_CURSOR" ,                  "CURSOR" , ":/images/crosshair_cur.bmp" } ,
    { "REVCROSSHAIR_CURSOR" ,               "CURSOR" , ":/images/crosshair_rev_cur.bmp" } ,
    { "POSITIONCROSSHAIRSNAP_CURSOR" ,      "CURSOR" , ":/images/position_cur.bmp" } ,
    { "REVPOSITIONCROSSHAIRSNAP_CURSOR" ,   "CURSOR" , ":/images/position_rev_cur.bmp" } ,
    { "CROSSHAIRENTITY_CURSOR" ,            "CURSOR" , ":/images/cur00001_cur.bmp" } ,
    { "REVCROSSHAIRENTITY_CURSOR" ,         "CURSOR" , ":/images/cur00001_rev_cur.bmp" } ,
    { "LEFTCLICK_CURSOR" ,                  "CURSOR" , ":/images/leftclick_cur.bmp" } ,
    { "REVLEFTCLICK_CURSOR" ,               "CURSOR" , ":/images/leftclick_rev_cur.bmp" } ,
    { "RIGHTCLICK_CURSOR" ,                 "CURSOR" , ":/images/rightclick_cur.bmp" } ,
    { "REVRIGHTCLICK_CURSOR" ,              "CURSOR" , ":/images/rightclick_rev_cur.bmp" } ,
    { "ZOOM_CURSOR" ,                       "CURSOR" , ":/images/zoom_cur.bmp" } ,
    { "REVZOOM_CURSOR" ,                    "CURSOR" , ":/images/zoom_rev_cur.bmp" } ,
    { "POSITIONCROSSHAIR_CURSOR" ,          "CURSOR" , ":/images/cur00002_cur.bmp" } ,
    { "REVPOSITIONCROSSHAIR_CURSOR" ,       "CURSOR" , ":/images/cur00002_rev_cur.bmp" } ,
    { "POSITIONCROSSHAIRENTITY_CURSOR" ,    "CURSOR" , ":/images/cur00003_cur.bmp" } ,
    { "REVPOSITIONCROSSHAIRENTITY_CURSOR" , "CURSOR" , ":/images/cur00003_rev_cur.bmp" } ,
    { "CROSSHAIRSNAP_CURSOR" ,              "CURSOR" , ":/images/cur00004_cur.bmp" } ,
    { "REVCROSSHAIRSNAP_CURSOR" ,           "CURSOR" , ":/images/cur00004_rev_cur.bmp" } ,
    { "ERASE_CURSOR" ,                      "CURSOR" , ":/images/erase_cur.bmp" } ,
    { "REVERASE_CURSOR" ,                   "CURSOR" , ":/images/erase_rev_cur.bmp" } ,
    { "POSITIONCROSSHAIRORIGIN_CURSOR" ,    "CURSOR" , ":/images/cur00005_cur.bmp" } ,
    { "REVPOSITIONCROSSHAIRORIGIN_CURSOR" , "CURSOR" , ":/images/cur00005_rev_cur.bmp" } ,
    { "POSITIONCROSSHAIRINT_CURSOR" ,       "CURSOR" , ":/images/cur00006_cur.bmp" } ,
    { "REVPOSITIONCROSSHAIRINT_CURSOR" ,    "CURSOR" , ":/images/cur00006_rev_cur.bmp" } ,
    { "CROSSHAIRORIGIN_CURSOR" ,            "CURSOR" , ":/images/cur00007_cur.bmp" } ,
    { "REVCROSSHAIRORIGIN_CURSOR" ,         "CURSOR" , ":/images/cur00007_rev_cur.bmp" } ,
    { "CROSSHAIRINT_CURSOR" ,               "CURSOR" , ":/images/cur00008_cur.bmp" } ,
    { "REVCROSSHAIRINT_CURSOR" ,            "CURSOR" , ":/images/cur00008_rev_cur.bmp" } ,
    { "" , "CURSOR" , "" } // last item
};
static int RC_NUM_NAMED_CURSOR_RESOURCES = sizeof(RCnamedCursorResources)/sizeof(RCnamedResourceImages);

static RCnumberedResourceImages RCnumberedCursorResources [] = {
    { 0 , "CURSOR" , "" } // last item
};
static int RC_NUM_NUMBERED_CURSOR_RESOURCES = sizeof(RCnumberedCursorResources)/sizeof(RCnumberedResourceImages);

#endif // RCSBITMAPRESOURCES_H
