//
// NOTE:
// this is the RealCAD static string resource definition file
// use this file in place of the Windows .rc file.
// This file was generated from a windows .rc file by rcstrtoc.exe
// if you edit it your changes may be overwritten later.
//

struct RCnamedSourceString {
    const char *name; // the name
    const char *str; // the resource string
};

static RCnamedSourceString RCnamedStringResources [] = {
    { "first" , "first named resource" } ,
    { "" , "" } // the last item
};
static int RC_NUM_NAMED_STRING_RESOURCES = sizeof(RCnamedStringResources)/sizeof(RCnamedSourceString);

struct RCnumberedSourceString {
    unsigned int id; // the number
    const char *str; // the resource string
};

static RCnumberedSourceString RCnumberedStringResources [] = {
    { 50 , "CAD" } ,
    //{ 51 , "CAD files (*.cad)|*.cad|" } ,
    { 51 , "CAD files (*.cad *.CAD)" } ,
    { 52 , "cad" } ,
    { 53 , "Untitled" } , 
    //{ 54 , "CAD files (*.cad)|*.cad|STL files (*.stl)|*.stl|DWG files (*.dwg)|*.dwg|DXF files *.dxf|*.dxf|IGES files (*.igs)|*.igs|" } ,
    //{ 54 , "CAD files (*.cad);;STL files (*.stl);;DWG files (*.dwg);;DXF files (*.dxf);;IGES files (*.igs)" } ,
    { 54 , "CAD files (*.cad);;DWG files (*.dwg);;DXF files (*.dxf);;IGES files (*.igs);;STL files (*.stl)" } ,
    { 100 , "Error opening the save file" } ,
    { 101 , "FILE SAVE" } , 
    { 102 , "File new" } , 
    { 103 , "%ls has changed - Save before clearing?" } ,
    { 104 , "File open" } , 
    { 105 , "%ls has changed - Save before clearing?" } ,
    { 106 , "File exit" } , 
    { 109 , "%ls has changed - Save before opening?" } ,
    { 110 , "%ls has changed - Save before leaving?" } ,
    { 111 , "File open from file list" } , 
    { 112 , "Mouse" } , 
    { 113 , "Metrecom" } , 
    { 114 , "Free space %ld bytes" } , 
    { 115 , "Free GDI resources %d%%" } , 
    { 116 , "Free System resources %d%%" } , 
    { 117 , "Free User resources %d%%" } , 
    { 118 , "Locate the point to reference from" } , 
    { 119 , "Select the reference entity to snap to" } , 
    { 120 , "Locate the position to snap to the reference entity or locate the intersecting entity" } , 
    { 121 , "Position along an entity" } , 
    { 122 , "Distance along" } , 
    { 123 , "Distance along dialog" } , 
    { 124 , "Select the reference entity" } , 
    { 125 , "Select the entity that defines the origin or midpoint, or locate the first positions" } , 
    { 126 , "Colour Selection Mask" } , 
    { 127 , "Layer selection mask" } , 
    { 128 , "Style Selection Mask" } , 
    { 129 , "Weight Selection Mask" } , 
    { 130 , "Colour Display Mask" } , 
    { 131 , "Layer Display Mask" } , 
    { 132 , "Style Display Mask" } , 
    { 133 , "Weight Display Mask" } , 
    { 134 , "Change colour" } , 
    { 135 , "Change layer" } , 
    { 136 , "Change style" } , 
    { 137 , "Change weight" } , 
    { 138 , "File new" } , 
    { 139 , "File open" } , 
    { 140 , "File save" } , 
    { 141 , "File save as..." } , 
    { 142 , "Print a view" } , 
    { 143 , "Printer setup" } , 
    { 144 , "Exit the software" } , 
    { 145 , "Open previous file" } , 
    { 146 , "<b>Undo</b><hr>Undo geometry operation" } ,
    { 147 , "<b>Redo</b><hr>Redo geometry operation" } ,
    { 148 , "Cut selected entities to clipboard" } , 
    { 149 , "Copy selected entities to clipboard" } , 
    { 150 , "Paste entities from clipboard" } , 
    { 151 , "<b>Delete</b><hr>Trash currently selected entities" } ,
    { 152 , "New attribute" } , 
    { 153 , "Delete attribute" } , 
    { 154 , "Edit attribute" } , 
    { 155 , "List attribute" } , 
    { 156 , "<b>Copy</b><hr>Copy selection by two points or coordinate entry" } ,
    { 157 , "<b>Project-Extrude</b><hr>Project selection and optionally copy" } ,
    { 158 , "<b>Scale</b><hr>Resize selection and optionally copy" } ,
    { 159 , "<b>Mirror</b><hr>Mirror selection and optionally copy" } ,
    { 160 , "<b>Rotate</b><hr>Rotate selection and optionally copy" } ,
    { 161 , "Cursor on viewplane" } , 
    { 162 , "Cursor on workplane" } , 
    { 163 , "<b>Select Workplane</b><hr>Select active workplane and edit settings" } ,
    { 164 , "<b>New Workplane</b><hr>Save a copy of an existing workplane with a new name" } ,
    { 165 , "<b>Move Workplane</b><hr>Relocate current workplane by its origin point" } ,
    { 166 , "<b>Orient Workplane</b><hr>Reposition current workplane by origin, X-axis and Y-axis" } ,
    { 167 , "<b>Reset Workplane</b><hr>Reset the current workplane to a standard workplane position" } ,
    { 168 , "<b>Delete Workplane</b><hr>Delete workplane" } ,
    { 169 , "Plane options or change" } , 
    { 170 , "Ruled surface options or change" } , 
    { 171 , "Surface of revolution options or change" } , 
    { 172 , "Text options or change" } , 
    { 173 , "Component options or change" } ,
    { 174 , "Dimension options or change" } , 
    { 175 , "<b>Grid</b><hr>Set or change the grid" } ,
    { 176 , "Define the system options" } , 
    { 177 , "<b>Select View</b><hr>Select a named view to display" } ,
    { 178 , "Cascade view windows" } , 
    { 179 , "Tile view windows" } , 
    { 180 , "<b>New View</b><hr>Save a copy of an existing view with a new name" } ,
    { 181 , "Change all view parameters" } , 
    { 182 , "Change view eye point" } , 
    { 183 , "Change view reference point" } , 
    { 184 , "<b>Position Viewer</b><hr>Place yourself precisely in the view" } ,
    { 185 , "Change view focal distance" } , 
    { 186 , "Change view clip planes" } , 
    { 187 , "Change view to perspective" } , 
    { 188 , "Change view to parallel" } , 
    { 189 , "<b>Rotate View</b><hr>Rotate the current view about an axis" } ,
    { 190 , "<b>Move</b><hr>Move selection by two points or coordinate entry" } ,
    { 200 , "Change view to workplane" } , 
    { 201 , "Change view by dynamic rotation" } , 
    { 202 , "<b>Walk About</b><hr>Walk around with cursor or follow path" } ,
    { 203 , "<b>Fly Over</b><hr>Fly around with cursor or follow flight path" } ,
    { 204 , "<b>Print Scale</b><hr>Set the scale you will print this view at" } ,
    { 205 , "<b>Reset View</b><hr>Reset the current view to a standard view position" } ,
    { 206 , "Change view depth" } ,
    { 207 , "<b>Delete View</b><hr>Delete views from the list" } ,
    { 208 , "Shade the current window" } , 
    { 209 , "Perform hidden line removal in the current window" } , 
    { 210 , "Move the tool menu" } , 
    { 211 , "Move the interrupt menu" } , 
    { 212 , "Move the quick menu" } , 
    { 213 , "Move the prompt line" } , 
    { 214 , "Help on this software" } , 
    { 215 , "About this software" } , 
    { 216 , "<b>Points</b><hr>Points Tools" } ,
    { 217 , "<b>Single Points</b><hr>Insert single points" } ,
    { 218 , "<b>Generate Points</b><hr>Generate points along an entity or between two positions" } ,
    { 219 , "<b>Lines</b><hr>Straight Line Tools" } ,
    { 220 , "<b>Insert Line</b><hr>Insert lines freely or constrained by modifiers" } ,
    { 221 , "<b>X-axis Line</b><hr>Insert lines constrained along the current X axis" } ,
    { 222 , "<b>Y-axis Line</b><hr>Insert lines constrained along the current Y axis" } ,
    { 223 , "<b>Angled Line</b><hr>Insert lines constrained by angle and optional length" } ,
    { 224 , "<b>Chamfer</b><hr>Insert chamfers between two lines, arc or curves and trims" } ,
    { 225 , "<b>Parallel Lines</b><hr>Insert multiple parallel lines at the same time" } ,
    { 226 , "<b>Rectangle</b><hr>Insert rectangles by sides or corners" } ,
    { 227 , "<b>Circles Arcs Ellipses</b><hr>Circle, Arc and Ellipse Tools" } ,
    { 228 , "<b>Circle by Center and Edge</b><hr>Insert circles by centre and edge point" } ,
    { 229 , "<b>Circle of Set Value</b><hr>Insert circles of preset size by center or two tangent edges" } ,
    { 230 , "<b>Circle by Three Edge Points</b><hr>Insert circles by three points" } ,
    { 231 , "Arc Commands" } , 
    { 232 , "<b>Arc by Center and Edge</b><hr>Insert arcs by center, start and end points" } ,
    { 233 , "<b>Arc of Set Value</b><hr>Insert arcs of preset size by center, start and end points" } ,
    { 234 , "<b>Arc by Three Points</b><hr>Insert arcs by start, edge and end points" } ,
    { 235 , "<b>Radius Fillet Arc</b><hr>Insert fillet Arcs between two lines, arcs or curves and trim" } ,
    { 236 , "<b>Curves</b><hr>Curve Tools" } ,
    { 237 , "<b>Curve by Control Points</b><hr>Insert curves using control points" } ,
    { 238 , "<b>Move Curve Points</b><hr>Accurately move control points of existing curves" } ,
    { 239 , "<b>Curved Surfaces</b><hr>Curved (non-planar) Surface Tools" } ,
    { 240 , "<b>Plane by Boundary</b><hr>Insert planes by entities that define the boundary" } ,
    { 241 , "<b>Ruled Surface</b><hr>Insert ruled surfaces between two linear or curved entities" } ,
    { 242 , "<b>Cylinder</b><hr>Insert cylinders on lines or between two positions" } ,
    { 243 , "<b>Revolved Surface</b><hr>Revolve a profile around an axis to form a surface" } ,
    { 244 , "<b>Elbow</b><hr>Insert circular revolved surfaces on arcs or by points" } ,
    { 245 , "<b>Text</b><hr>Text Tools" } ,
    { 246 , "<b>Text by Origin</b><hr>Insert Text at its origin point" } ,
    { 247 , "<b>Text Edit</b><hr>Edit existing text" } ,
    { 248 , "Component, Group and Bitmap Commands" } ,
    { 249 , "<b>Insert by Origin</b><hr>Insert components by origin point" } ,
    { 250 , "<b>Insert and Rotate</b><hr>Insert and orient components using two points" } ,
    { 251 , "<b>Insert Flip and Turn</b><hr>Insert rotate and flip components by three points" } ,
    { 252 , "<b>Create Group</b><hr>Create new group entities from selected entities" } ,
    { 253 , "<b>Add to Group</b><hr>Add entities to selected group" } ,
    { 254 , "<b>Remove from Group</b><hr>Remove entities from selected group" } ,
    { 255 , "<b>Ungroup</b><hr>Ungroups all entities in the group" } ,
    { 256 , "<b>Dimensions</b><hr>Dimension Tools" } ,
    { 257 , "<b>X-Axis Dimension</b><hr>Insert length dimensions constrained to X axis" } ,
    { 258 , "<b>Y-Axis Dimension</b><hr>Insert length dimensions constrained to Y axis" } ,
    { 259 , "<b>Angle Dimension</b><hr>Insert angle dimensions of positions, arcs or two lines" } ,
    { 260 , "Trim, Divide, Offset and Explode Commands" } , 
    { 261 , "<b>Trim</b><hr>Trim or extend entities to a position or another entity" } ,
    { 262 , "<b>Trim by Length</b><hr>Trim or extend entities to or by a given length" } ,
    { 263 , "<b>Divide by Entity</b><hr>Divide entities by a position or another entity" } ,
    { 264 , "<b>Divide by Length</b><hr>Divide entities to or by a given length" } ,
    { 265 , "<b>Divide by Number</b><hr>Divide equally into a given number of segments" } ,
    { 266 , "<b>Offset by Distance</b><hr>copy selection Offset by a preset distance" } ,
    { 267 , "<b>Offset</b><hr>Copy Selection offset by a digitized location" } ,
    { 268 , "<b>Locate Position</b><hr>Position Location Tools" } ,
    { 269 , "<b>Locate Reference Point</b><hr>Locate a point coordinate referenced from another point" } ,
    { 270 , "<b>Locate On</b><hr>Locate intersection of two entities or perpendicular to a position" } ,
    { 271 , "<b>Locate Along</b><hr>Locate a point accurately along a selected entity" } ,
    { 272 , "<b>Locate Origin Midpoint</b><hr>Locate a midpoint or origin of a selected entity" } ,
    { 273 , "<b>Zoom</b><hr>Zoom Tools" } ,
    { 274 , "<b>Zoom Window</b><hr>Zoom in to a region defined by two clicks" } ,
    { 275 , "<b>Pan Scroll</b><hr>Move the view around the view window" } ,
    { 276 , "Zoom in" } , 
    { 277 , "Zoom out" } , 
    { 278 , "<b>Zoom Scale</b><hr>Zoom to a specified scale value" } ,
    { 279 , "<b>Zoom Fit</b><hr>Fit the entire drawing into the active view window" } ,
    { 280 , "Repaint windows" } , 
    { 281 , "Selection masks" } , 
    { 282 , "Entity selection mask" } , 
    { 283 , "Colour selection mask" } , 
    { 284 , "Layer selection mask" } , 
    { 285 , "Style selection mask" } , 
    { 286 , "Weight selection mask" } , 
    { 287 , "Display masks" } , 
    { 288 , "Entity display mask" } , 
    { 289 , "Colour display mask" } , 
    { 290 , "Layer display mask" } , 
    { 291 , "Style display mask" } , 
    { 292 , "Weight display mask" } , 
    { 293 , "Default/Change colour" } , 
    { 294 , "Default/Change layer" } , 
    { 295 , "Default/Change style" } , 
    { 296 , "Default/Change weight" } , 
    { 297 , "<b>Ellipse by Three Points</b><hr>Insert ellipses by centre and two edge points" } ,
    { 298 , "<b>Ellipse of Set Value</b><hr>Insert ellipses of preset length width" } ,
    { 299 , "<b>Delete Segment</b><hr>Remove segments between two positions or entities" } ,
    { 300 , "<b>Zoom Previous</b><hr>Return to the previous zoom position" } ,
    { 301 , "Locate the second position or entity that defines the midpoint" } , 
    { 302 , "<b>Curve Degree</b><hr>Change the smoothness of curves by degree value" } ,
    { 303 , "<b>Regular Polygon</b><hr>Insert polygons with equal length sides" } ,
    { 304 , "<b>Stretch</b><hr>Move selection and stretch attached entities" } ,
    { 305 , "Regenerate window" } , 
    { 306 , "Regenerate all windows" } , 
    { 307 , "<b>Distance and Bearing</b><hr>Insert dimensions showing length and bearing angle" } ,
    { 308 , "<b>Radius with Leader</b><hr>Insert radius dimensions with leader lines" } ,
    { 309 , "<b>Diameter with Leader</b><hr>Insert diameter dimensions with leader lines" } ,
    { 310 , "<b>Diameter Dimension</b><hr>Insert diameter dimensions of arcs or circles" } ,
    { 311 , "<b>Locate End</b><hr>Locate the end point nearest to selection" } ,
    { 312 , "Locate the entity near the end to snap to" } , 
    { 313 , "<b>Select Layout</b><hr>Select a layout view to open and display" } ,
    { 314 , "<b>New Layout</b><hr>Create a new layout view" } ,
    { 315 , "<b>Delete Layout</b><hr>Delete layouts from the saved list" } ,
    { 316 , "<b>Add Viewport</b><hr>Place model views in the current layout" } ,
    { 317 , "<b>Orbit View</b><hr>Orbit around a point" } ,
    //{ 318 , "Raytrace the current view" } ,
    { 318 , "<b>Rayrace Render</b><hr>Realistically render a view to screen or file" } ,
    { 319 , "<b>Measure</b><hr>Measure and tally areas, lengths, angles and volumes" } ,
    { 320 , "Measure length, distance or area" } , 
    { 321 , "Measure angle" } , 
    { 322 , "Measure area" } , 
    { 323 , "Import DXF" } , 
    { 324 , "<b>New Zone</b><hr>Save the current zoom value and position" } ,
    { 325 , "<b>Zone Delete</b><hr>Delete zones from the list" } ,
    { 326 , "<b>Circle by Two Edge Points</b><hr>Insert circles by two edge points" } ,
    { 327 , "Default/Change lights" } , 
    { 328 , "Add/Change material parameters" } , 
    { 329 , "Import windows metafile" } , 
    { 330 , "Export DXF" } , 
    { 331 , "<b>Bring to Front</b><hr>Arrange selection on top of all other entities" } ,
    { 332 , "<b>Send to Back</b><hr>Arrange selection to bottom of all other entities" } ,
    { 333 , "<b>Forward One</b><hr>Arrange selection one level up from its current position" } ,
    { 334 , "<b>Back One</b><hr>Arrange selection one level down from its current position" } ,
    { 335 , "Insert raytracing light" } , 
    { 336 , "Patch options/change" } , 
    { 337 , "<b>Patch by Mesh</b><hr>Insert patch surfaces by rows of matching mesh points" } ,
    { 338 , "<b>Patch by Corners</b><hr>Insert patch surfaces by four corner points" } ,
    { 339 , "<b>Move Patch Points</b><hr>Reshape patch surfaces by moving patch control points" } ,
    { 340 , "<b>View Adjust Menu</b><hr>Opens the view adjust menu to manipulate view camera" } ,
    { 341 , "Walk forward" } , 
    { 342 , "Walk back" } , 
    { 343 , "Walk to the left" } , 
    { 344 , "Walk to the right" } , 
    { 345 , "Stand taller (Move up)" } , 
    { 346 , "Stand shorter (Move down)" } , 
    { 347 , "Look to the left" } , 
    { 348 , "Look to the right" } , 
    { 349 , "Look up" } , 
    { 350 , "Look down" } , 
    { 351 , "Shorten the focal distance" } , 
    { 352 , "Lengthen the focal distance" } , 
    { 353 , "Set the movement distance" } , 
    { 354 , "<b>Zoom to Zone</b><hr>Move current view to a saved position" } ,
    { 355 , "Toggle grid display" } , 
    { 356 , "Toggle grid snap" } , 
    { 357 , "Execute commands from a file" } , 
    { 358 , "Display standard view window" } , 
    { 359 , "Display standard view Top window" } , 
    { 360 , "Display standard view Front window" } , 
    { 361 , "Display standard view Left window" } , 
    { 362 , "Display standard view Right window" } , 
    { 363 , "Display standard view Back window" } , 
    { 364 , "Display standard view Bottom window" } , 
    { 365 , "Display standard view Iso window" } , 
    { 366 , "Display standard view Parallel window" } , 
    { 367 , "Display standard view Perspective window" } , 
    { 368 , "<b>Standard Views</b><hr>Standard view shortcut tools" } ,
    { 369 , "<b>Std Top</b><hr>Change view to Standard Top view" } ,
    { 370 , "<b>Std Front</b><hr>Change view to Standard Front view" } ,
    { 371 , "<b>Std Left</b><hr>Change view to Standard Left view" } ,
    { 372 , "<b>Std Right</b><hr>Change view to Standard Right view" } ,
    { 373 , "<b>Std Back</b><hr>Change view to Standard Back view" } ,
    { 374 , "<b>Std Bottom</b><hr>Change view to Standard Bottom view" } ,
    { 375 , "<b>Std Iso</b><hr>Change view to Standard Isometric view" } ,
    { 376 , "<b>Std Parallel</b><hr>Change view to Standard Parallel view" } ,
    { 377 , "<b>Std Perspective</b><hr>Change view to Standard Perspective view" } ,
    { 378 , "Select the window to reset first." } , 
    { 379 , "The zone does not exist." } , 
    { 380 , "Create Window" } , 
    { 381 , "This view no longer exists." } , 
    { 382 , "Please select the 3D window to reset first." } , 
    { 383 , "Reset Window" } , 
    { 384 , "<b>Plane by Interior</b><hr>Insert planes by clicking inside a closed boundary" } ,
    { 385 , "Import IGES" } , 
    { 386 , "Import HPGL" } , 
    { 387 , "Save default values" } , 
    { 388 , "<b>Explode</b><hr>Deconstruct entities into there originating entities" } ,
    { 389 , "Line options" } , 
    { 390 , "<b>Image</b><hr>Insert image files by a single origin point" } ,
    { 391 , "<b>Scaled Image</b><hr>Insert and size image by two points" } ,
    { 392 , "Group options" } , 
    { 393 , "Bitmap options" } , 
    { 394 , "<b>Delete Viewport</b><hr>Delete viewports from the current layout" } ,
    { 395 , "<b>Pan in Viewport</b><hr>Pan the model within a viewport" } ,
    { 396 , "<b>Change Viewport</b><hr>Change viewport settings" } ,
    { 397 , "<b>Curve Thru Points</b><hr>Insert curves passing through a series of points" } ,
    { 398 , "<b>Add Curve Points</b><hr>Add control points to existing curves" } ,
    { 399 , "<b>Chain Selection</b><hr>Select a chain of entities touching end to end" } ,
    { 400 , "None" } , 
    { 401 , "Arrow" } , 
    { 402 , "Open arrow" } , 
    { 403 , "Filled arrow" } , 
    { 404 , "Dot" } , 
    { 405 , "Filled Dot" } , 
    { 406 , "Slash" } , 
    { 407 , "Left" } , 
    { 408 , "Centre" } , 
    { 409 , "Right" } , 
    { 410 , "Bottom" } , 
    { 411 , "Centre" } , 
    { 412 , "Top" } , 
    { 413 , "None" } , 
    { 414 , "Plus/Minus" } , 
    { 415 , "Dual" } , 
    { 416 , "Upper/Lower" } , 
    { 417 , "Standard dimension terminator options" } , 
    { 418 , "Common point dimension terminator options" } , 
    { 419 , "Dimension prefix text options" } , 
    { 420 , "Dimension suffix text options" } , 
    { 421 , "Dimension prefix text entry options" } , 
    { 422 , "Dimension suffix text entry options" } , 
    { 423 , "Changing existing dimensions" } , 
    { 424 , "Dimension prefix verify" } , 
    { 425 , "Prefix" } , 
    { 426 , "Dimension suffix verify" } , 
    { 427 , "Suffix" } , 
    { 440 , "Centred" } , 
    { 441 , "To left" } , 
    { 442 , "To right" } , 
    { 443 , "Inside" } , 
    { 444 , "Outside" } , 
    { 445 , "Visible" } , 
    { 446 , "Hidden" } , 
    { 450 , "Top" } , 
    { 451 , "Bottom" } , 
    { 452 , "Front" } , 
    { 453 , "Back" } , 
    { 454 , "Left" } , 
    { 455 , "Right" } , 
    { 456 , "Iso" } , 
    { 457 , "Parallel" } , 
    { 458 , "Perspective" } , 
    { 459 , "Please select a 3D view to change" } , 
    { 460 , "View depth" } , 
    { 461 , "Enter View Depth" } , 
    { 462 , "Change drawing view" } , 
    { 463 , "The view border is too small in width" } , 
    { 464 , "The view border is too small in height" } , 
    { 500 , "Infinite Plane Verify" } , 
    { 501 , "Unknown entity type %d (Previous %d)" } , 
    { 502 , "Error reading entity type %d (Previous %d)" } , 
    { 503 , "Failed to allocate fixup table" } , 
    { 504 , "Failed to allocate entity load tables" } , 
    { 505 , "This is not a RealCAD file" } ,
    { 506 , "Nothing to %ls" } ,
    { 507 , "Unknown entity type %d in UNDO" } , 
    { 508 , "UNDO" } , 
    { 509 , "REDO" } , 
    { 510 , "No more previous zooms or views" } , 
    { 511 , "View and Zoom previous" } , 
    { 512 , "Failed to allocate entity load tables" } , 
    { 513 , "Progress %d%% complete" } , 
    { 550 , "Failed to sethdc HWND and HDC = NULL" } , 
    { 551 , "Select Command or Entities" } , 
    { 552 , "%ls : Untitled -   WP Top   Col 0 Lay 0   Sty 0 Wei 0   Grid %ls    Grid Snap %ls" } ,
    { 553 , "&Window" } , 
    { 554 , "%ls : %ls   WP %ls   Col %d Lay %d %ls Sty %d Wei %.2f   Grid %ls    Grid Snap %ls" } ,
    { 555 , "View %ls - Scale 1:%.2f Plot Scale %ls" } ,
    { 556 , "%ci" } , 
    { 557 , "Invalid coordinate" } , 
    { 558 , "Coordinate Entry" } , 
    { 559 , "Construct button menu" } , 
    { 560 , "Adding button" } , 
    { 561 , "Unknown Command" } , 
    { 562 , "Memory allocation : " } , 
    { 563 , "Button menu full : " } , 
    { 564 , "NEW CAD - Fatal Error" } , 
    { 565 , "NONE" } , 
    { 566 , "ENT-LOC" } , 
    { 567 , "SNAP" } , 
    { 568 , "DIG" } , 
    { 569 , "Internal : Memory allocation error" } , 
    { 570 , "Internal : Unknown resource string" } , 
    { 571 , "RealCAD - better faster smarter" } ,
    { 572 , "Student RealCAD - better faster smarter" } ,
    { 573 , "TriCad V3.0" } , 
    { 574 , "AUSCAD" } , 
    { 575 , "AUSCAD" } , 
    { 576 , "Student TriCad" } , 
    { 577 , "FlexiCAD" } , 
    { 578 , "RealCAD - better faster smarter" } ,
    { 579 , "Press control to make a copy of the entities being dragged" } , 
    { 580 , "This layer name already exists" } , 
    { 581 , "New layer" } , 
    { 582 , "This is not a correct layer name" } , 
    { 583 , "New layer name" } , 
    { 584 , "Change layer name" } , 
    { 585 , "New name" } , 
    { 600 , "The plot scale is incorrect" } , 
    { 601 , "The plot scale is too small" } , 
    { 602 , "The plot scale is too large" } , 
    { 603 , "RealCAD drawing" } ,
    { 604 , "The paper orientation does not correspond to the window orientation, Adjust ?" } , 
    { 605 , "Print" } , 
    { 606 , "The paper size is too small - Continue ?" } , 
    { 607 , "Please select a view to print" } , 
    { 608 , "There must be at least one pen" } , 
    { 609 , "There must be less than 10000 pens" } , 
    { 610 , "Print" } , 
    { 611 , "The student version allows printing on up to A4 size sheets only." } , 
    { 612 , "Locate the corner of the area to print" } , 
    { 650 , "&Options" } , 
    { 700 , "Please select only linear entities or plane entities" } , 
    { 701 , "Please select the entities that define the boundary first" } , 
    { 702 , "Not all the entities formed loops" } , 
    { 703 , "The entities are not planar" } , 
    { 704 , "Insert plane" } , 
    { 705 , "The selection must contain only planes" } , 
    { 706 , "Plane Change" } , 
    { 707 , "Locate the vertex of the plane" } , 
    { 750 , "Select the entity to trim" } , 
    { 751 , "Select the intersecting entity or the position to trim to" } , 
    { 752 , "Entity trim by incremental length" } , 
    { 753 , "Length to trim or extend" } , 
    { 754 , "Select the entity to trim by length" } , 
    { 755 , "Select the entity to divide" } , 
    { 756 , "Select the intersecting entity or the position to divide at" } , 
    { 757 , "Entity divide by incremental length" } , 
    { 758 , "Length to divide at" } , 
    { 759 , "Select the entity to divide by length" } , 
    { 760 , "Entity divide into a given number of sections" } , 
    { 761 , "Number of sections" } , 
    { 762 , "Select the entity to divide into sections" } , 
    { 763 , "Storing selection list or loops" } , 
    { 764 , "Please select only linear entities" } , 
    { 765 , "Offset profile" } , 
    { 766 , "Please select the entities to offset first" } , 
    { 767 , "Only one profile may be offset at a time" } , 
    { 768 , "Only planar profiles can be offset" } , 
    { 769 , "Select the position of the offset profile, from the selected entity" } , 
    { 770 , "Storing selection list or loops" } , 
    { 771 , "Please select only linear entities" } , 
    { 772 , "Please select the entities to offset first" } , 
    { 773 , "Only one profile may be offset at a time" } , 
    { 774 , "Only planar profiles can be offset" } , 
    { 775 , "Select the position of the offset profile, from the selected entity" } , 
    { 776 , "Break and delete rubberband structure" } , 
    { 777 , "Locate the linear entity to break and delete" } , 
    { 778 , "Locate the start position or first intersecting entity of the break" } , 
    { 779 , "Locate the end position or second intersecting entity of the break" } , 
    { 780 , "Select only linear entities to trim" } , 
    { 781 , "Trim entity to another entity" } , 
    { 782 , "Locate a position near the ends to be trimmed" } , 
    { 783 , "Select only linear entities to divide" } , 
    { 784 , "Trim entity by length or trim entity to length" } , 
    { 785 , "Locate near the end to move" } , 
    { 786 , "Locate near the end of the entities to divide" } , 
    { 787 , "Select the entities to explode" } , 
    { 788 , "Select the first entity to trim" } , 
    { 789 , "Select the second entity to trim" } , 
    { 790 , "Locate the start of the section line" } , 
    { 791 , "Locate the end of the section line" } , 
    { 792 , "Locate the first point of the section plane" } , 
    { 793 , "Locate the second point of the section plane" } , 
    { 794 , "Locate the third point of the section plane" } , 
    { 795 , "This section view name is too short" } , 
    { 796 , "Section" } , 
    { 800 , "Select the start of the line" } , 
    { 801 , "Select the end of the line" } , 
    { 802 , "Select the start of the horizontal line" } , 
    { 803 , "Select the end of the horizontal line" } , 
    { 804 , "Select the start of the vertical line" } , 
    { 805 , "Select the end of the vertical line" } , 
    { 806 , "Rubber band data for line angle" } , 
    { 807 , "Select the reference line" } , 
    { 808 , "Select the start of the angle constrained line" } , 
    { 809 , "Select the end of the angle constrained line" } , 
    { 810 , "Select the first line to chamfer" } , 
    { 811 , "Select the second line to chamfer" } , 
    { 812 , "Allocating rubber band data in line parallel" } , 
    { 813 , "Allocating dialog box in line parallel" } , 
    { 814 , "Allocating parallel line vertices" } , 
    { 815 , "Select the start of the parallel lines" } , 
    { 816 , "Select the end of the parallel lines" } , 
    { 817 , "Allocating rubberband data for line rectangle" } , 
    { 818 , "Allocating line entities in line rectangle" } , 
    { 819 , "Select the first corner of the rectangle" } , 
    { 820 , "Select the second corner of the rectangle" } , 
    { 821 , "Locate the centre of the polygon or the defining circle" } , 
    { 822 , "Locate the circumference of the polygon" } , 
    { 823 , "Locate third corner of the rectangle" } , 
    { 824 , "The rectangle is not defined as it has no area" } , 
    { 825 , "Insert rectangle" } , 
    { 850 , "Changing existing planes" } , 
    { 900 , "ABCDEFGHIJK\\r\\nabcdefghijk\\r\\n1234567890" } , 
    { 901 , "Changing existing text" } , 
    { 902 , "Prompt" } , 
    { 950 , "Radius is too small" } , 
    { 951 , "Circle Insert" } , 
    { 952 , "Select the centre of the circle" } , 
    { 953 , "Select a point on the circumference of the circle" } , 
    { 954 , "Insert circle by given radius" } , 
    { 955 , "Radius" } , 
    { 956 , "Select the centre of the circle or a tangent entity" } , 
    { 957 , "Select another tangent entity or point" } , 
    { 958 , "Select a point on the circumference of the circle" } , 
    { 959 , "Select another point on the circumference of the circle" } , 
    { 960 , "Select the last point on the circumference of the circle" } , 
    { 961 , "Diameter is too small" } , 
    { 962 , "Circle Insert Diameter" } , 
    { 963 , "Select a point on the circumference of the circle" } , 
    { 964 , "Select the opposite point on the circumference of the circle" } , 
    { 1000 , "Cannot match string '%ls'" } ,
    { 1001 , "Check numeric entry" } , 
    { 1002 , "Value out of range" } , 
    { 1050 , "Select view dialog" } , 
    { 1051 , "Create view dialog" } , 
    { 1052 , "This view already exists" } , 
    { 1053 , "Create view" } , 
    { 1054 , "Creating a new view" } , 
    { 1055 , "Please select a 3D view window to modify the view in" } , 
    { 1056 , "Change view all" } , 
    { 1057 , "View2 rubberband data" } , 
    { 1058 , "Please select a 3D view window to modify the view in" } , 
    { 1059 , "Change view all" } , 
    { 1060 , "These points do not define a view" } , 
    { 1061 , "Change view" } , 
    { 1062 , "Locate the new view eye point" } , 
    { 1063 , "Locate the new view reference point" } , 
    { 1064 , "Locate the new view up direction point" } , 
    { 1065 , "Please select a 3D view window to modify the view in" } , 
    { 1066 , "VIEW CHANGE EYE POINT" } , 
    { 1067 , "View3 rubberband data" } , 
    { 1068 , "Please select a 3D view window to modify the view in" } , 
    { 1069 , "Change view eye point" } , 
    { 1070 , "The new eye point does not define a view" } , 
    { 1071 , "Change view eye point" } , 
    { 1072 , "Locate the new view eye point" } , 
    { 1073 , "Please select a 3D view window to modify the view in" } , 
    { 1074 , "View change eye point" } , 
    { 1075 , "View4 rubberband data" } , 
    { 1076 , "Please select a 3D view window to modify the view in" } , 
    { 1077 , "Change view reference point" } , 
    { 1078 , "The new reference point does not define a view" } , 
    { 1079 , "Change view reference point" } , 
    { 1080 , "Locate the new view reference point" } , 
    { 1081 , "Enter the height of the eye position" } , 
    { 1082 , "Change view architectural perspective" } , 
    { 1083 , "Please select a 3D view window to modify the view in" } , 
    { 1084 , "Change view architectural perspective" } , 
    { 1085 , "These points do not define a view" } , 
    { 1086 , "Change view" } , 
    { 1087 , "This view cannot be changed to a perspective" } , 
    { 1088 , "Change view architectural perspective" } , 
    { 1089 , "Locate the new view eye point" } , 
    { 1090 , "Locate the new view reference point" } , 
    { 1091 , "Please select a 3D view window to modify the view in" } , 
    { 1092 , "Change view eye point" } , 
    { 1093 , "Change view focal distance" } , 
    { 1094 , "Focal distance" } , 
    { 1095 , "Focal distance dialog box" } , 
    { 1096 , "The focal distance does not define a view" } , 
    { 1097 , "Change view reference point" } , 
    { 1098 , "Please select a 3D view window to modify the view in" } , 
    { 1099 , "Change view clip planes" } , 
    { 1100 , "View clip dialog box" } , 
    { 1101 , "The clip planes do not define a view" } , 
    { 1102 , "Change view clip planes" } , 
    { 1103 , "Please select a 3D view window to modify the view in" } , 
    { 1104 , "Change view to perspective" } , 
    { 1105 , "This view cannot be changed to perspective" } , 
    { 1106 , "Change view to perspective" } , 
    { 1107 , "Perspective focal distance" } , 
    { 1108 , "Focal distance" } , 
    { 1109 , "Perspective focal distance dialog box" } , 
    { 1110 , "The focal distance does not define a view" } , 
    { 1111 , "Change view reference point" } , 
    { 1112 , "Please select a 3D view window to modify the view in" } , 
    { 1113 , "Change view to parallel" } , 
    { 1114 , "This view cannot be changed to parallel" } , 
    { 1115 , "Please select a 3D view window to modify the view in" } , 
    { 1116 , "Change view to perspective" } , 
    { 1117 , "Change view rotation rubberband data" } , 
    { 1118 , "Change view rotation" } , 
    { 1119 , "View rotation angle" } , 
    { 1120 , "Change view rotation dialog" } , 
    { 1121 , "Please select a 3D view window to modify the view in" } , 
    { 1122 , "Change view to perspective" } , 
    { 1123 , "The view rotation failed" } , 
    { 1124 , "Change view rotation" } , 
    { 1125 , "Locate a position to continue the view rotation" } , 
    { 1126 , "Locate the start of the rotation axis or a line" } , 
    { 1127 , "Locate the end of the rotation axis" } , 
    { 1128 , "Please select a 3D view window to modify the view in" } , 
    { 1129 , "<b>Align View to Workplane</b><hr>Align active view to be planar to current workplane" } ,
    { 1130 , "Please select a workplane" } , 
    { 1131 , "Workplane focal distance" } , 
    { 1132 , "Focal distance" } , 
    { 1133 , "Workplane focal distance dialog box" } , 
    { 1134 , "The focal distance does not define a view" } , 
    { 1135 , "Change view reference point" } , 
    { 1136 , "View change dynamics rubberband data" } , 
    { 1137 , "Please select a 3D view window to modify the view in" } , 
    { 1138 , "Change view dynamics" } , 
    { 1139 , "Use the cursor to dynamically rotate the view" } , 
    { 1140 , "View change dynamics rubberband data" } , 
    { 1141 , "Please select a 3D view window to modify the view in" } , 
    { 1142 , "Change view dynamics" } , 
    { 1143 , "View change dynamic walk" } , 
    { 1144 , "Walk step distance" } , 
    { 1145 , "Dialog for dynamic walk" } , 
    { 1146 , "Use the cursor to dynamically walk through the view" } , 
    { 1147 , "View change dynamics rubberband data" } , 
    { 1148 , "Please select a 3D view window to modify the view in" } , 
    { 1149 , "Change view dynamics" } , 
    { 1150 , "View change dynamic fly" } , 
    { 1151 , "Fly step distance" } , 
    { 1152 , "Dialog for dynamic fly" } , 
    { 1153 , "Use the cursor to dynamically fly through the view" } , 
    { 1154 , "Please select a 3D view window to change the plot scale in" } , 
    { 1155 , "Change view plot scale" } , 
    { 1156 , "New view plot scale" } , 
    { 1157 , "Change view plot scale" } , 
    { 1158 , "Please select a 3D view window to modify the view in" } , 
    { 1159 , "Change view reset to standard" } , 
    { 1160 , "Reset to standard view dialog" } , 
    { 1161 , "Delete view dialog" } , 
    { 1162 , "You cannot delete a view that has an associated window" } , 
    { 1163 , "Delete view" } , 
    { 1164 , "Really delete view '%ls'" } ,
    { 1165 , "Delete view" } , 
    { 1166 , "Locate the corner of the zoom window" } , 
    { 1167 , "Locate the opposite corner of the zoom window" } , 
    { 1168 , "Locate the start of the scroll direction - Press control or drag to start dynamic scroll" } , 
    { 1169 , "Locate the end of the scroll direction" } , 
    { 1170 , "Locate the new centre of the view to zoom in - Press control or drag to start dynamic zoom" } , 
    { 1171 , "Locate the new centre of the view to zoom out - Press control or drag to start dynamic zoom" } , 
    { 1172 , "Change zoom scale" } , 
    { 1173 , "Zoom scale" } , 
    { 1174 , "Locate the new centre of the view to zoom to scale" } , 
    { 1175 , "Please select a window to fit" } , 
    { 1176 , "Zoom fit entities" } , 
    { 1177 , "Please select the window to regenerate" } , 
    { 1178 , "Regenerate window" } , 
    { 1179 , "Layout-" } ,
    { 1180 , "Create layout drawing" } ,
    { 1181 , "This drawing already exists" } , 
    { 1182 , "Too many views - No more views can be created" } , 
    { 1183 , "Delete layout drawing" } ,
    { 1184 , "This drawing is still displayed in a window and so it cannot be deleted" } , 
    { 1185 , "Really delete layout drawing %ls?" } ,
    { 1186 , "Allocating rubberband data for add view" } , 
    { 1187 , "Layout drawing add view" } ,
    { 1188 , "This is not a layout drawing window" } ,
    { 1189 , "The clip boundary is too narrow" } , 
    { 1190 , "The clip boundary is too short" } , 
    { 1191 , "Select the position of the view reference point on the drawing" } , 
    { 1192 , "Select the first corner of the view clip boundary" } , 
    { 1193 , "Select the second corner of the view clip boundary" } , 
    { 1194 , "Too many views - No more views can be created" } , 
    { 1195 , "Create layout drawing" } ,
    { 1196 , "Select the window that defines the zone first" } , 
    { 1197 , "Create View Zone" } , 
    { 1198 , "This zone already exists for this view - Overwrite this zone?" } , 
    { 1199 , "Select the window that defines the zones first" } , 
    { 1200 , "Delete View Zone" } , 
    { 1201 , "Really delete zone '%ls' from '%ls'" } ,
    { 1202 , "View change Modify incremental" } , 
    { 1203 , "Failed to create the view modify incremental button menu" } , 
    { 1204 , "Please select a window that displays the 3D view to change " } , 
    { 1205 , "3D view change Modify incremental" } , 
    { 1206 , "3D view change Modify incremental Distance options " } , 
    { 1207 , "View modify distance" } , 
    { 1208 , "Select the window to zoom first" } , 
    { 1209 , "Zoom to zone" } , 
    { 1210 , "This view has no zones defined" } , 
    { 1211 , "Move the mouse to scroll the image" } , 
    { 1212 , "Move the mouse to zoom the image" } , 
    { 1213 , "Viewport not located - Select by clicking on viewport HANDLE" } ,
    { 1214 , "Locate a HANDLE of the viewport to DELETE" } ,
    { 1215 , "Locate a HANDLE of the viewport to SCROLL" } ,
    { 1216 , "Locate the start of the scroll" } , 
    { 1217 , "Locate the end of the scroll" } , 
    { 1218 , "Locate a HANDLE of the viewport to CHANGE" } ,
    //{ 1219 , "CAD files *.CAD|*.CAD|" } ,
    { 1219 , "CAD files (*.cad *.CAD)" } ,
    { 1220 , "Select the title block component " } ,
    { 1221 , "Locate a HANDLE of the viewport to Zoom-FIT" } ,
    { 1222 , "Locate a HANDLE of the viewport to MOVE" } ,
    { 1223 , "Locate the start of the alignment line" } , 
    { 1224 , "Locate the end of the alignment line" } , 
    { 1225 , "Locate the position on the 3d view to snap to the alignment line" } , 
    { 1226 , "Zoom Fit a 3d view on a layout drawing" } ,
    { 1227 , "Pan in a viewport on a layout drawing" } ,
    { 1228 , "Move a viewport on a layout drawing" } ,
    { 1229 , "Align a viewport on a layout drawing" } ,
    { 1230 , "Change viewport settings" } ,
    { 1250 , "Enter text dialog" } ,
    { 1251 , "Locate the position for the text" } , 
    { 1252 , "The selection must contain only text or dimension leaders" } , 
    { 1253 , "Text Change" } , 
    { 1254 , "Please select the text to edit before selecting the command" } , 
    { 1255 , "Text edit" } , 
    { 1256 , "Edit text dialog" } , 
    { 1257 , "Edit text" } , 
    { 1258 , "Locate the position for the component annotation text" } ,
    { 1259 , "Please select the single component annotation text entity to edit first" } ,
    { 1260 , "Component annotation text edit" } ,
    { 1261 , "Please select only a single component annotation text entity" } ,
    { 1262 , "Please select a component annotation text entity" } ,
    { 1263 , "Edit component annotation text" } ,
    { 1300 , "Select the origin of the arc" } , 
    { 1301 , "Select a point on the circumference of the arc" } , 
    { 1302 , "Select the start of the arc" } , 
    { 1303 , "Select the end of the arc" } , 
    { 1304 , "Insert arc by centre, radius and end" } , 
    { 1305 , "Radius" } , 
    { 1306 , "Select the origin of the arc" } , 
    { 1307 , "Select the start of the arc" } , 
    { 1308 , "Select the end of the arc" } , 
    { 1309 , "Select the start of the arc" } , 
    { 1310 , "Select a point on the circumference of the arc" } , 
    { 1311 , "Select the end of the arc" } , 
    { 1312 , "Insert fillet arc" } , 
    { 1313 , "Fillet radius" } , 
    { 1314 , "Select the first entity to fillet" } , 
    { 1315 , "Select the second entity to fillet" } , 
    { 1316 , "Select the approximate origin point of the arc" } , 
    { 1317 , "Select the second tangent line or circle" } , 
    { 1350 , "Top" } , 
    { 1351 , "Bottom" } , 
    { 1352 , "Front" } , 
    { 1353 , "Back" } , 
    { 1354 , "Left" } , 
    { 1355 , "Right" } , 
    { 1356 , "Iso" } , 
    { 1357 , "Select workplane dialog" } , 
    { 1358 , "Create workplane dialog" } , 
    { 1359 , "This workplane already exists" } , 
    { 1360 , "Create workplane" } , 
    { 1361 , "Creating a new workplane" } , 
    { 1362 , "Select the new workplane origin" } , 
    { 1363 , "Select the new workplane origin" } , 
    { 1364 , "Select the new workplane xaxis" } , 
    { 1365 , "Select the new workplane yaxis" } , 
    { 1366 , "Reset to standard workplane dialog" } , 
    { 1367 , "Delete workplane dialog" } , 
    { 1368 , "You cannot delete the current workplane" } , 
    { 1369 , "Delete workplane" } , 
    { 1370 , "Really delete workplane '%ls'" } ,
    { 1371 , "Delete workplane" } , 
    { 1372 , "Select the entity that defines the workplane" } , 
    { 1400 , "Locate the start of the translation" } , 
    { 1401 , "Locate the end of the translation" } , 
    { 1402 , "Project options" } , 
    { 1403 , "Locate the start of the projection" } , 
    { 1404 , "Locate the end of the projection" } , 
    { 1405 , "Locate the start of the line or a line defining the plane" } , 
    { 1406 , "Locate the end of the line defining the plane" } , 
    { 1407 , "Locate the first point on the plane, or locate a circle, or locate a plane" } , 
    { 1408 , "Locate the second point on the plane" } , 
    { 1409 , "Locate the last point on the plane" } , 
    { 1410 , "Locate the centre of rotation" } , 
    { 1411 , "Locate the start of the rotation axis" } , 
    { 1412 , "Locate the end of the rotation axis" } , 
    { 1413 , "Locate the origin of the rotation or the rotation arc toward the start of the rotation" } , 
    { 1414 , "Locate the start of the rotation" } , 
    { 1415 , "Locate the end of the rotation" } , 
    { 1416 , "Locate the centre of the scale operation" } , 
    { 1417 , "Locate the start of the stretch" } , 
    { 1418 , "Locate the end of the stretch" } , 
    { 1419 , "Locate the start of the line that defines the scale factor" } , 
    { 1420 , "Locate the end of the line that defines the scale factor" } , 
    { 1450 , "Select the position of the point" } , 
    { 1451 , "Select the position on the entity or the intersecting entity" } , 
    { 1452 , "Generate points" } , 
    { 1453 , "Number of points" } , 
    { 1454 , "Select the initial position, or a linear entity" } , 
    { 1455 , "Select the final position" } , 
    { 1456 , "Select only linear entities to generate points on" } , 
    { 1457 , "Generate points" } , 
    { 1500 , "Changing existing ruled surfaces" } , 
    { 1550 , "No match" } , 
    { 1600 , "Select component" } ,
    { 1601 , "Changing existing components" } ,
    { 1650 , "Failed to allocate rubber band data for srev command1" } , 
    { 1651 , "Locate the start of the rotation axis, the rotation line or the rotation arc" } , 
    { 1652 , "Locate the end of the rotation axis" } , 
    { 1653 , "Locate the generating entity" } , 
    { 1654 , "Allocating surface of revolution data" } , 
    { 1655 , "Insert elbow options" } , 
    { 1656 , "Enter elbow radius" } , 
    { 1657 , "Allocating surface of revolution dialog" } , 
    { 1658 , "Locate the origin of the elbow or an arc" } , 
    { 1659 , "Locate a circumference point of the elbow" } , 
    { 1660 , "Locate the start of the elbow" } , 
    { 1661 , "Locate the end of the elbow" } , 
    { 1662 , "The selection must contain only surfaces of revolution" } , 
    { 1663 , "Surface of revolution change" } , 
    { 1664 , "Select linear entities only" } , 
    { 1665 , "Insert surface of revolution" } , 
    { 1666 , "Please select the linear entities to rotate first" } , 
    { 1700 , "Locate the first entity of the ruled surface" } , 
    { 1701 , "Locate the second entity of the ruled surface" } , 
    { 1702 , "Allocating ruled surface data" } , 
    { 1703 , "Insert cylinder options" } , 
    { 1704 , "Enter cylinder radius" } , 
    { 1705 , "Allocating ruled surface dialog" } , 
    { 1706 , "Locate the start of the pipe or a line" } , 
    { 1707 , "Locate the end of the pipe" } , 
    { 1708 , "The selection must contain only ruled surfaces" } , 
    { 1709 , "Ruled surface change" } , 
    { 1750 , "Changing existing surfaces of revolution" } , 
    { 1800 , "Internal Error : INLIST not empty" } , 
    { 1801 , "Cannot allocate edge table" } , 
    { 1850 , "Allocating dimension 1 rubber band data" } , 
    { 1851 , "Select the position of the dimension or the line to dimension" } , 
    { 1852 , "Select the point to dimension" } , 
    { 1853 , "Select the position of the dimension" } , 
    { 1854 , "Allocating dimension 1 rubber band data" } , 
    { 1855 , "Select the position of the dimension or the line to dimension" } , 
    { 1856 , "Select the point to dimension" } , 
    { 1857 , "Select the position of the dimension" } , 
    { 1858 , "Allocating dimension 3 rubber band data" } , 
    { 1859 , "Select the position of the dimension or the arc, or first line to dimension" } , 
    { 1860 , "Select the origin of the angular dimension" } , 
    { 1861 , "Select the position to dimension" } , 
    { 1862 , "Select the position of the angular dimension" } , 
    { 1863 , "The selection must contain only linear dimensions" } , 
    { 1864 , "Linear Dimension Change" } , 
    { 1865 , "Locate the start of the distance bearing dimension" } , 
    { 1866 , "Locate the end of the distance bearing dimension" } , 
    { 1867 , "Rubberband memory" } , 
    { 1868 , "R" } , 
    { 1869 , "Locate the circle to dimension" } , 
    { 1870 , "Locate the position of the dimension text" } , 
    { 1871 , "Rubberband memory" } , 
    { 1872 , "f" } , 
    { 1873 , "Symbol" } , 
    { 1874 , "Locate the circle to dimension" } , 
    { 1875 , "Locate the position of the dimension text" } , 
    { 1876 , "Rubberband memory" } , 
    { 1877 , "Locate the circle to dimension" } , 
    { 1878 , "Locate the second line to dimension" } , 
    { 1879 , "Locate the position of the angular dimension" } , 
    { 1880 , "Select the position of the dimension or the line to dimension" } , 
    { 1881 , "Select the orientation position of the dimension" } , 
    { 1882 , "Select the point to dimension" } , 
    { 1883 , "Select the position of the dimension" } , 
    { 1884 , "Locate the start of the leader" } , 
    { 1885 , "Locate the corner of the leader" } , 
    { 1886 , "Locate the position of the text" } , 
    { 1900 , "Select the entities to attach the new attribute to first" } , 
    { 1901 , "New Attribute" } , 
    { 1902 , "Select the entities to delete the attributes from" } , 
    { 1903 , "Delete Attribute" } , 
    { 1904 , "Delete all the attributes from each of the selected entities" } , 
    { 1905 , "This entity has no attributes" } , 
    { 1906 , "Attribute %d of %d" } , 
    { 1907 , "Select the entity to delete the attributes from" } , 
    { 1908 , "Edit Attribute" } , 
    { 1909 , "Select only a single entity to edit the attributes of" } , 
    { 1910 , "Edit Attribute" } , 
    { 1911 , "This entity has no attributes" } , 
    { 1912 , "Attribute %d of %d" } , 
    { 1913 , "Select the entity to list the attributes from" } , 
    { 1914 , "List Attribute" } , 
    { 1915 , "Select only a single entity to list the attributes of" } , 
    { 1916 , "This entity has no attributes" } , 
    { 1917 , "Attribute %d of %d" } , 
    { 1950 , "Please select a window to shade" } , 
    { 1951 , "Window shade" } , 
    //{ 1952 , "Windows bitmap files (*.BMP)|*.bmp|Targa files (*.TGA)|*.tga|" } ,
    { 1952 , "Windows bitmap files (*.BMP *.bmp);;Targa files (*.TGA *.tga)" } ,
    { 1953 , "bmp" } ,
    { 1954 , "Select the the image filename to save as" } , 
    { 2000 , "Please select a window to hide" } , 
    { 2001 , "Window hide" } , 
    { 2050 , "Attached entities were not deleted" } , 
    { 2051 , "Select the position to use as the origin of the entities" } , 
    { 2052 , "Select the position to paste the entities" } , 
    { 2100 , "Allocating component 1 rubber band data" } ,
    { 2101 , "Locate the position to place the component.  (Use F5-F9 and F11 to rotate.)" } ,
    { 2102 , "Allocating component 2 rubber band data" } ,
    { 2103 , "Locate the position to place the component" } ,
    { 2104 , "Locate the orientation of the component" } ,
    { 2105 , "Allocating component 3 rubber band data" } ,
    { 2106 , "Locate the position to place the component" } ,
    { 2107 , "Locate the X orientation of the component" } ,
    { 2108 , "Locate the plane orientation of the component" } ,
    { 2109 , "The selection must contain only components" } ,
    { 2110 , "Component Change" } ,
    { 2150 , "Allocating curve 1 rubber band data" } , 
    { 2151 , "Curve degree" } , 
    { 2152 , "Curve insert" } , 
    { 2153 , "Allocating curve 1 rubber band data" } , 
    { 2154 , "Select the start of the curve" } , 
    { 2155 , "Select the next control point of the curve" } , 
    { 2156 , "Allocating curve 2 rubber band data" } , 
    { 2157 , "Please select the curve to modify first" } , 
    { 2158 , "Curve move control point" } , 
    { 2159 , "Please select only one curve to modify" } , 
    { 2160 , "Curve move control point" } , 
    { 2161 , "Please select a single curve to modify" } , 
    { 2162 , "Curve move control point" } , 
    { 2163 , "Locate the curve control point to move" } , 
    { 2164 , "Locate the new position of the control point" } , 
    { 2165 , "Please select curves only" } , 
    { 2166 , "Curve change degree" } , 
    { 2167 , "Enter the new degree" } , 
    { 2168 , "Locate the first point on the curve" } , 
    { 2169 , "Locate the next point on the curve" } , 
    { 2170 , "Locate the curve control point next to the new control point" } , 
    { 2171 , "Locate the other curve control point next to the new control point" } , 
    { 2172 , "Locate the the new control point" } , 
    { 2173 , "Curve insert control point" } , 
    { 2174 , "Please select the lines, circles or arcs to convert first" } , 
    { 2175 , "Please select the curve to modify first" } , 
    { 2200 , "Allocating rubberband information" } , 
    { 2201 , "Locate the origin of the ellipse" } , 
    { 2202 , "Locate the size and orientation of the ellipse" } , 
    { 2203 , "Locate a circumference point on the ellipse" } , 
    { 2204 , "Allocating rubberband information" } , 
    { 2205 , "Locate the origin of the ellipse" } , 
    { 2206 , "Locate the orientation of the ellipse" } , 
    { 2250 , "Change group options" } , 
    { 2300 , "Insert group entity" } , 
    { 2301 , "Select the entities to group first" } , 
    { 2302 , "Add entity to group" } , 
    { 2303 , "Select the group entity to add entities to first" } , 
    { 2304 , "Remove entity from group" } , 
    { 2305 , "Select only one group entity to remove entities from" } , 
    { 2306 , "Remove entity from group" } , 
    { 2307 , "Select a group entity to remove entities from" } , 
    { 2308 , "Select the entity to add to the group" } , 
    { 2309 , "Select the group entity to remove entities from" } , 
    { 2310 , "Remove entity from group" } , 
    { 2311 , "Select only one group entity to remove entities from" } , 
    { 2312 , "Remove entity from group" } , 
    { 2313 , "Select a group entity to remove entities from" } , 
    { 2314 , "Remove entity from group" } , 
    { 2315 , "Select the entity to remove from the group" } , 
    { 2316 , "Select the group entities to ungroup first" } , 
    { 2317 , "Ungroup entities" } , 
    { 2318 , "Please select group entities only" } , 
    { 2319 , "Change group" } , 
    { 2400 , "Select the first position, or entity to measure" } , 
    { 2401 , "Select the second position to measure" } , 
    { 2402 , "Select the first corner of the angle to measure, or a line" } , 
    { 2403 , "Select the origin of the angle to measure" } , 
    { 2404 , "Select the last corner of the angle to measure" } , 
    { 2405 , "Select the second line that defines the angle " } , 
    { 2406 , "Select the plane, ruled surface, or surface of revolution to measure." } , 
    { 2407 , "Select only linear or surface entities to measure" } , 
    { 2408 , "Measure length, distance or area" } , 
    { 2409 , "Select only surface entities to measure" } , 
    { 2410 , "Measure area" } , 
    { 2500 , "Import DXF" } , 
    { 2501 , "%ls has changed - Save before clearing" } ,
    //{ 2502 , "Autocad DXF Files (*.DXF)|*.dxf|" } ,
    { 2502 , "AutoCAD DXF Files (*.DXF *.dxf)" } ,
    { 2503 , "dxf" } ,
    { 2504 , "Export DXF" } , 
    { 2600 , "Don't Save" } , 
    { 2601 , "Windows Bitmap" } , 
    { 2602 , "Bumpmap" } , 
    //{ 2603 , "Bumpmap files (*.BMF)|*.bmf|" } ,
    { 2603 , "Bumpmap files (*.BMF *.bmf)" } ,
    { 2604 , "Save image file as" } ,
    //{ 2605 , "Windows Bitmap files (*.BMP)|*.bmp|" } ,
    //{ 2605 , "Windows Bitmap files (*.BMP *.bmp)" } ,
    { 2605 , "Image files (*.bmp *.jpg *.jpeg *.png);;Bitmap files (*.bmp);;JPEG files (*.jpg *.jpeg);;PNG files (*.png)" } ,
    { 2606 , "Select background image" } ,
    { 2607 , "The selection must consist of light entities only." } , 
    { 2608 , "Change Light" } , 
    { 2611 , "Phong" } , 
    { 2612 , "General" } , 
    { 2613 , "Select bumpmap file" } , 
    //{ 2614 , "Bumpmap files (*.BMF)|*.bmf|" } ,
    { 2614 , "Bumpmap files (*.BMF *.bmf)" } ,
    { 2615 , "Select texture map" } ,
    { 2616 , "2D texture map" } , 
    { 2617 , "Solid wood texture" } , 
    { 2618 , "Insert Light" } , 
    { 2619 , "Enter the height of the light" } , 
    { 2620 , "Locate the position of the light" } , 
    { 2621 , "Locate the direction of the light" } , 
    { 2622 , "Locate the size of the cone angle of the light" } , 
    { 2623 , "The selection must consist of surface entities only." } , 
    { 2624 , "Change surface property options" } , 
    { 2625 , "Change texture map options" } , 
    { 2626 , "Change bump map options" } , 
    { 2627 , "Please select a window to raytrace." } , 
    { 2628 , "Raytrace" } , 
    { 2629 , "There are no lights defined - only background lighting will be used." } , 
    { 2630 , "The image file cannot be created" } , 
    { 2631 , "The memory buffer could not be allocated - Out of memory." } , 
    { 2632 , "The image file could not be written - Check disk space." } , 
    { 2633 , "None" } , 
    { 2634 , "Crazy" } , 
    { 2635 , "Spotted" } , 
    { 2636 , "Bumpy" } , 
    { 2637 , "Stucco" } , 
    { 2638 , "Wrinkled" } , 
    { 2639 , "Marble" } , 
    { 2640 , "Only uncompressed 24 bit bitmap files are supported as textures and backgrounds.." } , 
    { 2641 , "The bitmap file cannot be found." } , 
    { 2642 , "An error occurred while reading the bitmap file." } , 
    { 2643 , "There is not enough memory to load the bitmap." } , 
    { 2700 , "Select the entities to move to the front first." } , 
    { 2701 , "Arrange To front" } , 
    { 2702 , "Select the entities to move to the back first" } , 
    { 2703 , "Arrange To back" } , 
    { 2704 , "Select the entities to move forward one position first" } , 
    { 2705 , "Arrange Forward one" } , 
    { 2706 , "Select the entities to move backward one position first." } , 
    { 2707 , "Arrange Backward one" } , 
    { 2800 , "The length of each column of the patch must be the same." } , 
    { 2801 , "Patch insert by polygon mesh" } , 
    { 2802 , "Locate the first row of the polygon mesh - Abort at the end of each row." } , 
    { 2803 , "Locate the points of the polygon mesh - Abort at the end of each row." } , 
    { 2804 , "The selection must contain only patches" } , 
    { 2805 , "Patch change" } , 
    { 2806 , "Changing existing patches" } , 
    { 2807 , "The patch is too small" } , 
    { 2808 , "Locate the first corner of the patch" } , 
    { 2809 , "Locate the second corner of the patch" } , 
    { 2810 , "Locate the third corner of the patch" } , 
    { 2811 , "Locate the fourth corner of the patch" } , 
    { 2812 , "Move patch control points" } , 
    { 2813 , "Please select the patch to modify first." } , 
    { 2814 , "Please select a single patch to modify" } , 
    { 2815 , "Please select a patch to modify" } , 
    { 2816 , "Select the patch control points to move" } , 
    { 2817 , "Locate the base point of the movement of the patch control points" } , 
    { 2818 , "Locate the end of the movement of the patch control points" } , 
    { 2900 , "The command file could not be opened." } , 
    { 2901 , "Execute commands from file" } , 
    { 2902 , "Unknown select command on line %d -  '%ls'" } ,
    { 2903 , "Unknown abort command on line %d - '%ls'" } ,
    { 2904 , "Unknown format command on line %d - '%ls'" } ,
    { 2905 , "Unknown position command on line %d - '%ls'" } ,
    { 2906 , "Unknown scale command on line %d - '%ls'" } ,
    { 2907 , "Dialog command expected on line %d - '%ls'" } ,
    { 2908 , "Dialog control number expected on line %d - ' %ls'" } ,
    { 3000 , "Import HPGL" } , 
    //{ 3001 , "HPGL Files *.hpg *.hp *.hpgl *.plt|*.hpg;*.hp;*.hpgl;*.plt|" } ,
    { 3001 , "HPGL Files (*.hpg *.hp *.hpgl *.plt)" } ,
    { 3002 , "hpg" } ,
    { 3100 , "Import IGES" } , 
    //{ 3101 , "IGES Files (*.IGS)|*.igs|" } ,
    { 3101 , "IGES Files (*.IGS *.igs)" } ,
    { 3102 , "igs" } ,
    { 3200 , "Locate a corner of the grid" } , 
    { 3201 , "Locate the opposite corner of the grid" } , 
    { 3202 , "Locate the start of the wall" } , 
    { 3203 , "Locate the end of the wall" } , 
    { 3204 , "Locate the wall on which to insert the door." } , 
    { 3205 , "Locate the position to insert the door." } , 
    { 3206 , "Indicate the orientation of the door" } , 
    { 3207 , "Locate the wall on which to insert the window" } , 
    { 3208 , "Locate the position to insert the window" } , 
    { 3209 , "Insert Window" } , 
    { 3210 , "Window height" } , 
    { 3211 , "Select the walls to insert the roof over first" } , 
    { 3212 , "Insert roof" } , 
    { 3213 , "Select only walls to insert the roof over" } , 
    { 3214 , "The walls must form a single closed loop." } , 
    { 3215 , "Change existing walls" } , 
    { 3216 , "Locate the origin of the component" } ,
    { 3217 , "Locate the first direction of the component" } ,
    { 3218 , "Locate the second direction of the component" } ,
    { 3219 , "Ground" } , 
    { 3220 , "Invalid floor" } , 
    { 3221 , "Floor out of range" } , 
    { 3222 , "New Floor" } , 
    { 3223 , "This floor already exists" } , 
    { 3224 , "There is no more room for new floors" } , 
    { 3225 , "Floor %d" } , 
    { 3226 , "Locate the top of the stairs" } , 
    { 3227 , "Locate the bottom of the stairs" } , 
    { 3228 , "Locate the side to place the stairs" } , 
    { 3229 , "Change view architectural perspective" } , 
    { 3230 , "Please select a window to modify the view in" } , 
    { 3231 , "These points do not define a view" } , 
    { 3232 , "This view cannot be changed to a perspective" } , 
    { 3233 , "Locate the new view eye point" } , 
    { 3234 , "Locate the new view reference point" } , 
    { 3235 , "Select the wall to trim" } , 
    { 3236 , "Select the position or wall to trim to" } , 
    { 3237 , "Select the wall to trim" } , 
    { 3238 , "Select the position or wall to trim to and break" } , 
    { 3239 , "Select the first wall to trim to a corner" } , 
    { 3240 , "Select the second wall to trim to a corner" } , 
    { 3241 , "Select the walls, lines, arcs and circles to insert the floor over first" } , 
    { 3242 , "Insert floor" } , 
    { 3243 , "Select only walls, lines, arcs or circles to insert the floor over" } , 
    { 3244 , "Select the walls, lines, arcs or circles to insert the ceiling over first" } , 
    { 3245 , "Insert ceiling" } , 
    { 3246 , "Select only walls, lines, arcs or circle to insert the ceiling over" } , 
    { 3247 , "Locate the start of the section" } , 
    { 3248 , "Locate the end of the section" } , 
    { 3249 , "Select the entities to detail" } , 
    { 3250 , "New detail" } , 
    { 3251 , "Locate the origin of the detail" } , 
    { 3252 , "Locate the view point of the elevation" } , 
    { 3253 , "Locate the direction of the elevation" } , 
    { 3254 , "Select the notation to change" } , 
    { 3255 , "Change existing columns" } , 
    { 3266 , "Locate the position of the column" } , 
    { 3267 , "Locate the orientation of the column" } , 
    { 3268 , "Locate the corner of the column grid" } , 
    { 3269 , "Locate the opposite corner of the column grid" } , 
    { 3270 , "Please select the entities to change first" } , 
    { 3271 , "Change architect layer and attributes" } , 
    { 3272 , "Remove from left side of wall" } , 
    { 3273 , "Remove from right side of wall" } , 
    { 3274 , "Add component detail to the wall" } ,
    { 3275 , "Plan door swing one" } , 
    { 3276 , "Plan door swing two" } , 
    { 3277 , "Plan door swing three" } , 
    { 3278 , "Plan door swing four" } , 
    { 3279 , "3D door closed, swing one" } , 
    { 3280 , "3D door closed, swing two" } , 
    { 3281 , "3D door closed, swing three" } , 
    { 3282 , "3D door closed, swing four" } , 
    { 3283 , "3D door open, swing one" } , 
    { 3284 , "3D door open, swing two" } , 
    { 3285 , "3D door open, swing three" } , 
    { 3286 , "3D door open, swing four" } , 
    { 3287 , "Exploding points " } , 
    { 3289 , "Distance" } , 
    { 3290 , "Locate the reference point" } , 
    { 3291 , "Select the door or window to label" } , 
    { 3292 , "Locate the position of the label" } , 
    { 3293 , "Locate the lower left corner of the table" } , 
    { 3294 , "Single" } , 
    { 3295 , "Double with landing" } , 
    { 3296 , "Spiral" } , 
    { 3297 , "Locate the corner of the top step" } , 
    { 3298 , "Locate the corner on the landing" } , 
    { 3299 , "Locate the side to place the stairs" } , 
    { 3300 , "Locate the centre of the stairs" } , 
    { 3301 , "Locate the corner of the top step" } , 
    { 3302 , "Locate the direction of the steps" } , 
    { 3303 , "VisualisationOne" } , 
    { 3304 , "Locate the first corner of the area to dimension" } , 
    { 3305 , "Locate the second corner of the area to dimension" } , 
    { 3306 , "Don't copy" } , 
    { 3500 , "Left" } , 
    { 3501 , "Centre" } , 
    { 3502 , "Right" } , 
    { 3503 , "Bottom" } , 
    { 3504 , "Centre" } , 
    { 3505 , "Top" } , 
    { 3506 , "Changing existing bitmaps" } , 
    //{ 3507 , "Bitmap files *.bmp|*.bmp|JPEG files *.jpg|*.jpg|PNG files *.png|*.png|" } ,
    { 3507 , "Image files (*.bmp *.jpg *.jpeg *.png);;Bitmap files (*.bmp);;JPEG files (*.jpg *.jpeg);;PNG files (*.png)" } ,
    { 3508 , "Select bitmap" } ,
    { 3509 , "Locate the position of the bitmap" } , 
    { 3510 , "Locate the corner of the bitmap" } , 
    { 3511 , "Locate the opposite corner of the bitmap" } , 
    { 3512 , "None" } , 
    { 3513 , "Single" } , 
    { 3514 , "Double" } , 
    { 3600 , "Select the short cut command " } , 
    { 3601 , "Select the short cut command to add to the menu" } , 
    { 3602 , "Select the short cut command to remove from the menu" } , 
    { 4000 , "Locate an entity on the chain of entities to select" } , 
    { 4001 , "Customize background click" } , 
    { 4002 , "Convert to Curves" } ,
    { 4003 , "High" } , 
    { 4004 , "Low" } , 
    { 4005 , "Toggle drag detail" } , 
    { 4006 , "Search and replace text or attributes" } , 
    { 4007 , "No entities were found" } , 
    { 4008 , "The fit option requires a window to be selected first." } , 
    { 4009 , "Edit information" } , 
    { 4010 , "<b>Component Annotation</b><hr>Define component annotation text with prompts" } ,
    { 4011 , "<b>Edit Annotation</b><hr>Edit component annotation text" } ,
    { 4012 , "Run CAD Basic program" } , 
    { 4013 , "Edit CAD Basic program" } , 
    { 4014 , "New CAD Basic program" } , 
    { 4015 , "Stop CAD Basic program" } , 
    { 4016 , "Pause CAD Basic program" } , 
    { 4017 , "Step CAD Basic program" } , 
    { 4018 , "Run CAD Basic program" } , 
    { 4019 , "Save CAD Basic program" } , 
    { 4020 , "Save as CAD Basic program" } , 
    { 4021 , "Evaluate CAD basic variable" } , 
    { 4022 , "Automatic dynamic scroll" } , 
    { 4023 , "<b>Locate Intersection</b><hr>Locate the real intersection point of two entities" } ,
    { 4024 , "Automatic dynamic zoom" } , 
    { 4025 , "Locate the intersection point" } , 
    { 4026 , "Load application" } , 
    { 4027 , "Default values have been saved" } , 
    { 4028 , "File Save Options" } , 
    { 4029 , "Copy 2D Window" } , 
    { 4030 , "Copy 2D" } , 
    { 4031 , "Locate the first corner of the area to copy" } , 
    { 4032 , "Locate the opposite corner of the area to copy" } , 
    { 4033 , "Show custom menu" } , 
    { 4034 , "Add command to custom menu" } , 
    { 4035 , "Delete command from custom menu" } , 
    { 4036 , "<b>Parallel Dimension</b><hr>Insert length dimension parallel to selection or two points" } ,
    { 4037 , "Display command window" } , 
    { 4038 , "Display layer window" } , 
    { 4039 , "An error occurred while saving the file.  Check disk space and/or disk is inserted." } , 
    { 4040 , "<b>Radius Dimension</b><hr>Insert radius dimensions of arcs and circles" } ,
    { 4041 , "<b>Leader Label</b><hr>Insert text as a label with leader lines" } ,
    { 4042 , "<b>Trim to Corner</b><hr>Trim or extend two entities to a common corner" } ,
    { 4043 , "<b>Intersection</b><hr>Generate planar intersection and section view" } ,
    { 4044 , "<b>Zoom Fit Viewport</b><hr>Fit the entire model into the selected viewport" } ,
    { 4045 , "Print preview" } , 
    { 4046 , "Print preview Selection" } , 
    { 4047 , "Print" } , 
    { 4048 , "Printer Setup" } , 
    { 4049 , "Scale" } , 
    { 4050 , "Close" } , 
    { 4051 , "Copy bitmap to the clipboard" } , 
    { 4052 , "Display compose drawing floating menu" } , 
    { 4053 , "Find text in files" } , 
    { 4054 , "<b>Save New Component</b><hr>Save Selected entities as a new separate .CAD file" } ,
    { 4055 , "Import Medusa File" } , 
    { 4056 , "Dynamic rotate about axis" } , 
    { 4057 , "<b>Plane by Vertex Points</b><hr>Insert plane by corner (vertex) points" } ,
    { 4058 , "<b>Move Dimension Text</b><hr>Move only dimension text to a new location" } ,
    { 4059 , "Export IGES" } , 
    { 4060 , "Export HPGL" } , 
    { 4061 , "Show raytrace menu" } , 
    { 4062 , "Default/Change Style Set" } , 
    { 4063 , "Stroked IGES Output" } , 
    { 4064 , "Unload application" } , 
    { 4065 , "<b>Incremental Counter</b><hr>Insert text with prefix, suffix and incrementing numbers" } ,
    { 4066 , "<b>Insert and Scale</b><hr>Insert orient and size component by two points" } ,
    { 4067 , "<b>Text by Rotation</b><hr>Insert and orient text by two points" } ,
    { 4068 , "Locate the orientation point of the text" } , 
    { 4069 , "<b>Array</b><hr>Copy selection in a defined pattern" } ,
    { 4070 , "<b>Locate Offset Point</b><hr>Locate a point offset from two entities" } ,
    { 4071 , "<b>Copy Along</b><hr>Copy selection by spacing or quantity along an entity" } ,
    { 4072 , "Import DWG" } , 
    { 4073 , "Export DWG" } ,
    { 4074 , "<b>Transform</b><hr>Transformation and Copy Tools" } ,
    { 4075 , "<b>Dynamic View</b><hr>Dynamic View Tools" } ,
    { 4076 , "<b>Workplane</b><hr>Workplane Tools" } ,
    { 4077 , "<b>Layout</b><hr>Layout Tools" } ,
    { 4078 , "<b>View Window</b><hr>View Window Tools" } ,
    { 4079 , "Render Commands" } , 
    { 4080 , "Clone Command" } , 
    { 4081 , "<b>Components</b><hr>Component Tools" } ,
    { 4082 , "<b>Attachments</b><hr>Attachment Tools" } ,
    { 4083 , "Leader Options" } , 
    { 4084 , "<b>Locate Apparent Intersection</b><hr>Locate where two entities visually appear to intersect in the view" } ,
    { 4085 , "<b>Poly Fence Selection</b><hr>Select entities inside a closed poly selection window" } ,
    { 4086 , "Locate the next vertex of the selection window" } , 
    { 4087 , "<b>Trim-Extend-Divide-Explode...</b><hr>Trim, Extend, Divide, Explode and More Edit Tools" } ,
    { 4088 , "Keyboard Shortcuts" } , 
    { 4089 , "There are no entities selected.  Select the entities before selecting the command." } , 
    { 4090 , "<b>Set Workplane on Entity</b><hr>Reposition current workplane using and existing entity" } ,
    { 4091 , "<b>Move Viewport</b><hr>Move viewports around your layout" } ,
    { 4092 , "Rename Layout Drawing" } ,
    { 4093 , "New from Template" } , 
    { 4094 , "Insert light at Sun Position" } , 
    { 4095 , "<b>Align Viewport</b><hr>Align viewports with two points or a line in the layout" } ,
    { 4096 , "Change Snap Settings" } , 
    { 4097 , "<b>Remove Islands</b><hr>Remove and fill islands (holes in planes" } ,
    { 4098 , "<b>Locate XYZ Reference</b><hr>Locate a point referenced from three model locations" } ,
    { 4099 , "Copy Layout Drawing" } ,
    { 4100 , "<b>Panel</b><hr>Insert a special group called panel" } ,
    { 4101 , "Show Properties" } , 
    { 4102 , "Change anchor point" } , 
    { 4103 , "Switch Screens" } , 
    { 4104 , "Default/Change Entity" } ,
    { 4105 , "Change General Properties" } ,
    { 4106 , "Change Background Colour" } ,
    { 4107 , "*Varies*" } ,
    { 4108 , "Default Font: " } ,
    { 4109 , "Choose Other Font" } ,
    { 4110 , "Default Value: %1" } ,
    { 4111 , "Text Options" } ,
    { 4112 , "1/2" } ,
    { 4113 , "1/3" } ,
    { 4114 , "1/4" } ,
    { 4115 , "1/5" } ,
    { 4116 , "1/6" } ,
    { 4117 , "1/7" } ,
    { 4118 , "1/8" } ,
    { 4119 , "1/9" } ,
    { 4120 , "1/10" } ,
    { 4121 , "File Tools" } ,
    { 4122 , "File Email" } ,
    { 4123 , " View %ls - "},
    { 4124 , "Zoom 1:%.2f " },
    { 4125 , " Print Scale %ls " } ,
    { 4126 , "Clone colour command" } ,
    { 4127 , "Clone layer command" } ,
    { 4128 , "Clone style command" } ,
    { 4129 , "Clone weight command" } ,
    { 4130 , "Define pattern line style command" } ,
    { 4131 , "Model Size" } ,
    { 4132 , "Paper Size" } ,
    { 4133 , "Clone all command" } ,
    { 5000 , "Untitled" } ,
    { 5001 , "Cannot save the CadBasic program" } ,
    { 5002 , "Save CadBasic program" } ,
    { 5003 , "Error saving the CadBasic program." } ,
    { 5004 , "CadBasic programs *.bas|*.bas|" } ,
    { 5005 , "bas" } ,
    { 5006 , "Save CadBasic program" } ,
    { 5007 , "The current CadBasic program has changed.  Save the program before clearing?" } ,
    { 5008 , "Open CadBasic program" } ,
    { 5100 , "<b>View Style</b><hr>View Style Tools" } ,
    { 5101 , "<b>Wireframe</b><hr>Sets view with all lines displayed" } ,
    { 5102 , "<b>Hidden Line</b><hr>Sets view with hidden lines removed" } ,
    { 5103 , "<b>Dashed Hidden Line</b><hr>Sets view with hidden lines dashed" } ,
    { 5104 , "<b>Shaded Surface</b><hr>Sets view with shaded surfaces only" } ,
    { 5105 , "<b>Shaded with Lines</b><hr>Sets view with shaded surfaces and lines" } ,
    { 5106 , "<b>Shaded Dashed Lines</b><hr>Sets view with shaded surfaces and dashed lines" } ,
    { 5107 , "<b>Texture Shaded</b><hr>Sets view with textured surfaces" } ,
    { 5108 , "<b>Textured with Lines</b><hr>Sets view with textured surfaces and lines" } ,
    { 5109 , "<b>Virtual Reality 3D</b><hr>Sets view to use with 3D glasses" } ,
    { 5110 , "<b>View as Perspective</b><hr>Switch view to perspective projection" } ,
    { 5111 , "<b>View as Parallel</b><hr>Switch view to parallel projection" } ,
    { 5112 , "<b>Shade Options</b><hr>Set the basic shading parameters" } ,
    { 5120 , "<b>Position Viewer</b><hr>Locate position of viewer and see from his perspective" } ,
    { 5121 , "<b>Look Around</b><hr>Look around the view from the same position" } ,
    { 5122 , "<b>Section Plane</b><hr>Insert section planes to visually slice the model and expose interior" } ,
    { 5130 , "<b>Capture</b><hr>Scene and image capture tools" } ,
    { 5131 , "<b>Capture View</b><hr>Copy entire view ready to paste into other programs" } ,
    { 5132 , "<b>Capture Area</b><hr>Copy a selected area ready to paste into other programs" } ,
    { 5133 , "<b>Capture Bitmap</b><hr>Copy a view as a bitmap image to save or paste into other programs" } ,
    { 5134 , "<b>Rayrace Render</b><hr>Realistically render a view to screen or file" } ,
    { 5135 , "<b>Camera Path</b><hr>Set or change camera's travel path and camera settings" } ,
    { 5136 , "<b>Reference Path</b><hr>Set or change where the camera is pointing" } ,
    { 5137 , "<b>Object Path</b><hr>Set or change the actions of group entities in the scene" } ,
    { 5138 , "<b>Path Path</b><hr>Set or change the actions of patch entities in the scene" } ,
    { 5139 , "<b>Record Animation</b><hr>Action. Dry run or record the animation to a file" } ,
    { 5140 , "<b>Replay Animation File</b><hr>View the recorded animation video file" } ,
    { 5150 , "<b>Planes</b><hr>Hatching/Planar Surface Tools" } ,
    { 5151 , "<b>Groups</b><hr>Group Tools" } ,
    { 5152 , "<b>Previous View State</b><hr>Return view to previous zoom and position" } ,
    { 5153, "<b>Arrange</b><hr>Arrange the display order of entities in the drawing" } ,
    { 5154, "<b>Copy Layout</b><hr>Save a copy of an existing layout with a new name" } ,
    { 5155, "<b>Rename Layout</b><hr>Change the names of existing layout views" } ,
    { 5156, "<b>Full Screen</b><hr>Toggle full screen mode" } ,
    { 5160, "<b>File</b><hr>File Tools" } ,
    { 5161, "<b>File New</b><hr>Start a new blank drawing" } ,
    { 5162, "<b>File New From Template</b><hr>Start a new drawing with presets from a template" } ,
    { 5163, "<b>File Open</b><hr>Open or import a CAD, DXF, DWG or other drawing file" } ,
    { 5164, "<b>File Save</b><hr>Update the currently active CAD file" } ,
    { 5165, "<b>File Save As</b><hr>Save or export the current drawing as a new file" } ,
    { 5166, "<b>Preview View</b><hr>Print-preview the entire active view area" } ,
    { 5167, "<b>Preview Scaled Region</b><hr>Print-preview a scaled area of the view" } ,
    { 5168, "<b>File Export</b><hr>Export CAD files to other supported file formats" } ,
    { 5169, "<b>File Import</b><hr>Import files from other supported CAD formats" } ,
    { 5170, "<b>File Commands</b><hr>open RealCAD .CMD command files" } ,
    { 5171, "<b>File Exit</b><hr>Exit the program" } ,
    { 5172, "<b>Find in Files</b><hr>Find CAD files that contain specific text in them" } ,
    { 5173, "<b>File Info</b><hr>Display information about the currently open CAD file" } ,
    { 5174, "<b>File Tools</b><hr>File utility and enhancement tools" } ,
    { 5175, "<b>Preference Settings</b><hr>Set or change preference settings" } ,
    { 5176, "<b>System Options</b><hr>Set or change system preferences" } ,
    { 5177, "<b>File Email</b><hr>Send the current drawing by email to a recipient" } ,
    { 5178, "<b>Top Perspective</b><hr>Standard Top Perspective View" } ,
    { 5179, "Import SKP" } ,
    { 5180, "<b>3D Warehouse</b><hr>Download an skp file from the SketchUp 3D Warehouse" } ,
    { 5181, "Select All" } ,
    { 5182, "Add Vertex" } ,
    { 5183, "Delete Vertex" } ,
    { 5184, "Move Vertex" } ,
    { 5185, "Copy Plane Boundary" } ,
    { 5186, "Detach Entities" } ,
    { 5187, "White Out" } ,
    { 5188, "Small" } ,
    { 5189, "Medium" } ,
    { 5190, "Large" } ,
    { 5191, "Change Select Colour" } ,
    { 5192, "<b>Flat Pattern</b><hr>Generate a flat pattern outline from a ruled surface" } ,
    { 5193, "<b>Insert Spiral</b><hr>Generate a spiral tube surface" } ,
    { 5194, "<b>Convert to Curves</b><hr>Convert lines, circles arcs or Text into curves" } ,
    { 5195, "<b>Plane by Segment</b><hr>Insert planes clicking on segments of a boundary" } ,
    { 999999, "<br><em>(This feature is not currently available)</em>" } ,
    //{ 999999, "<br><em>(This feature will be available in a future version)</em>" } ,
    { 0 , "" } // last item
};
static int RC_NUM_NUMBERED_STRING_RESOURCES = sizeof(RCnumberedStringResources)/sizeof(RCnumberedSourceString);
